kubev2v/forklift-documentation

- documentation/doc-Forklift/master.adoc
- documentation/docinfo.html
Adds docinfo.html to fill in headers in the generated HTML for better search engine indexing
> Add rich tags for headers

- README.md
> OKE --> OKD II

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-source-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-vddk-to-mtv.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-virt-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/common-attributes.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-migration-plan.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-network-mapping.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-storage-mapping.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-console.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/mtv-resources-and-services.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/mtv-workflow.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/running-migration-plan.adoc
I've done a review of the complete documentation. Most notable changes are:
- Add a section to select migration network
- Add `if` statement for u/s vs d/s, since the namespace where the operator is installed is different
Next step: work on the Troubleshooting section.
> 20200216 - Review - Fabien Dupont

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-storage-mapping.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1929981
Preview build: http://file.tlv.redhat.com/~apinnick/bz1929981-mtv-storage-defaults_doc-Migration_Toolkit_for_Virtualization/#creating-storage-mapping_mtv
> BZ1929981: MTV storage support

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/about-storage.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-source-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-vddk-to-mtv.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-virt-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-storage-mapping.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-console.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1929981
Doc preview: http://file.tlv.redhat.com/~apinnick/org-changes_doc-Migration_Toolkit_for_Virtualization/#about-storage_mtv
> BZ1929981: storage defaults

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/mtv-prerequisites.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/mtv-resources-and-services.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/mtv-workflow.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1931873
Preview build: http://file.tlv.redhat.com/~apinnick/bz1931873-supported-os_doc-Migration_Toolkit_for_Virtualization/#mtv-prerequisites_mtv
> BZ1931873: link to supported OSes

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
Changes proposed in an email from Ilanit Stein.
> Ilanit's comments on CLI migration

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-console.adoc
Merge pull request #69 from apinnick/peer-review-fixes
> Fix table col widths

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
Updated migration plan parameters
Doc preview: http://file.tlv.redhat.com/~apinnick/migration-plan-parameters_doc-Migration_Toolkit_for_Virtualization/#migrating-virtual-machines-cli_mtv-cli
> Update migration plan parameters

- _config.yml
- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/common-attributes.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-console.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/uninstalling-mtv-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/uninstalling-mtv-ui.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1931536
Doc preview: http://file.tlv.redhat.com/~apinnick/bz1931536-uninstall_doc-Migration_Toolkit_for_Virtualization/#uninstalling-mtv_mtv-cli
> BZ1931536: Uninstall MTV

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-vddk-to-mtv.adoc
Reverts konveyor/forklift-documentation#92
> Revert "Bug 1946273 - Replace busybox with UBI for VDDK image build"

- _config.yml
- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-source-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/common-attributes.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/using-must-gather.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1935027
Preview: https://deploy-preview-109--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#using-must-gather_forklift
> Bz1935027 must gather

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-cli.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1948601
Previews:
https://deploy-preview-102--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#installing-mtv-cli_forklift
https://deploy-preview-102--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift
> Bz1948601 api version

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-console.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/obtaining-console-url.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1948444
For beta and 2.0.0
Preview: https://deploy-preview-100--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#accessing-console_forklift
> BZ1948444: Accessing MTV console

- _config.yml
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-virt-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-migration-plan.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1953350
beta and 2.0
Change previews:
https://deploy-preview-111--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#adding-virt-provider_forklift (Adding virt provider)
https://deploy-preview-111--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#creating-migration-plan_forklift (Migration plan prerequisites)
> BZ1953350: Default OCPv provider (beta)

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/common-attributes.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/known-issues.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1953975
Preview: https://deploy-preview-112--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#known-issues_forklift
> BZ#1953975: First VM migration is incomplete in Migration CR

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/known-issues.adoc
Comment out known issues and delete bug about incomplete VM status
> Removed known issues with missing VM status.

- _config.yml
- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-source-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-virt-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-migration-plan.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-network-mapping.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-storage-mapping.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/selecting-migration-network-for-source-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/selecting-migration-network-for-virt-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/uninstalling-mtv-ui.adoc
https://issues.redhat.com/browse/MIGENG-1001
Ready for QE
Preview: https://deploy-preview-115--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#adding-virt-provider_forklift (subsection in "Adding virt provider"
> Migeng 1001 select network

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/canceling-migration-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/canceling-migration-ui.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-console.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
https://issues.redhat.com/browse/MTV-51
Preview build: hthttps://deploy-preview-82--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#canceling-migration-ui_forklift
> MTV-51: Cancel migration

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/about-storage.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/about-warm-migration.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-source-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-virt-provider.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/common-attributes.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/creating-migration-plan.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/error-messages.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migration-prerequisites.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/running-migration-plan.adoc
https://issues.redhat.com/browse/MTV-50 (warm migration)
https://bugzilla.redhat.com/show_bug.cgi?id=1941935 (memory changes not migrated)
https://bugzilla.redhat.com/show_bug.cgi?id=1958662 (CBT limit)
https://bugzilla.redhat.com/show_bug.cgi?id=1959230 (cutover scheduled from CLI)
https://bugzilla.redhat.com/show_bug.cgi?id=1959232 (snapshot interval from CLI)
https://bugzilla.redhat.com/show_bug.cgi?id=1957859 (CBT must be enabled)
Previews:
About warm migration: https://deploy-preview-108--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#about-warm-migration_forklift
Migration prerequisites: https://deploy-preview-108--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migration-prerequisite …
> MTV-50: Warm migration

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/common-attributes.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/mtv-resources-and-services.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/technology-preview.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/using-must-gather.adoc
https://issues.redhat.com/browse/MIGENG-1002
Note: Docs validation to be done after [QE validation of feature](https://issues.redhat.com/browse/MIGENG-996).
Tech preview note to be added.
Doc preview: https://deploy-preview-80--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#mtv-resources-and-services_forklift
> MIGENG-1002: Validation service

- documentation/modules/creating-network-mapping.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1971526
Creating a NAD for multiple network mappings in the UI.
Preview: https://deploy-preview-146--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#creating-network-mapping_forklift
> BZ1971526: Create NAD for network maps in UI

- documentation/modules/migrating-virtual-machines-cli.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1971321 (new NAD)
https://bugzilla.redhat.com/show_bug.cgi?id=1971324 (storage and network map CRs)
https://bugzilla.redhat.com/show_bug.cgi?id=1971326 (plan CR)
Ready for QE.
Preview: https://deploy-preview-145--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift
> BZ1971321, BZ1971324, BZ1971326: updated CRs

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/creating-network-mapping.adoc
- documentation/modules/known-issues.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
Updated network attachment definition info in migration with CLI and UI.
Added BZ to Troubleshooting > Known Issues.
Previews:
https://deploy-preview-153--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#creating-network-mapping_forklift
https://deploy-preview-153--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift
https://deploy-preview-153--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#known-issues_forklift
> NAD update

- documentation/modules/known-issues.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
https://issues.redhat.com/browse/MTV-70
Add CBT bug and workaround to Known Issues.
Preview: https://deploy-preview-156--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#known-issues_forklift
> MTV-70: CBT workaround

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-vddk-to-mtv.adoc
- documentation/modules/creating-migration-plan.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
https://issues.redhat.com/browse/MTV-74
Update VDDK instructions
Previews:
https://deploy-preview-161--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#adding-vddk-to-mtv_forklift
https://deploy-preview-161--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift (Prerequisites)
https://deploy-preview-161--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#creating-migration-plan_forklift (Prerequisites)
> MTV-74: Update VDDK procedure

- documentation/modules/migrating-virtual-machines-cli.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1981075
2.0 and next release
https://deploy-preview-174--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift
> BZ1981075: Note about name/namespace for CRs

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/upgrading-mtv-ui.adoc
https://issues.redhat.com/browse/MTV-68
Preview: https://deploy-preview-180--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#upgrading-mtv-ui_forklift
> MTV-68: Upgrade MTV operator

- documentation/modules/using-must-gather.adoc
https://issues.redhat.com/browse/MTV-67
Preview: https://deploy-preview-152--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#using-must-gather_forklift
Ready for QE.
> MTV-67: Filter must-gather data collection

- documentation/modules/using-must-gather.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1995576
Add note about filtered must-gather with incorrect value.
Preview: https://deploy-preview-192--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#using-must-gather_forklift
> BZ1995576: filtered must-gather note

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/adding-vddk-to-mtv.adoc
- documentation/modules/canceling-migration-cli.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/creating-migration-plan.adoc
- documentation/modules/creating-network-mapping.adoc
- documentation/modules/creating-storage-mapping.adoc
- documentation/modules/error-messages.adoc
- documentation/modules/increasing-esxi-nfc-service-memory.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/migration-environment-requirements.adoc
- documentation/modules/obtaining-console-url.adoc
- documentation/modules/selecting-migration-network-for-source-provider.adoc
- documentation/modules/selecting-migration-network-for-virt-provider.adoc
- documentation/modules/selecting-migration-network.adoc
- documentation/modules/storage-support.adoc
- documentation/modules/uninstalling-mtv-ui.adoc
- documentation/modules/virt-migration-workflow.adoc
- documentation/modules/warm-migration.adoc
https://issues.redhat.com/browse/MTV-66
Preview build: https://deploy-preview-151--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/
> MTV-66: RHV cold migration

- documentation/doc-Release_notes/master.adoc
- documentation/modules/rn-2.0.adoc
https://deploy-preview-200--forklift-documentation.netlify.app/documentation/doc-release_notes/master
> adding 2.0 RN

- documentation/modules/creating-migration-plan.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/virt-migration-workflow.adoc
https://issues.redhat.com/browse/MTV-49
Add minimal hook documentation
Preview: https://deploy-preview-154--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#creating-migration-plan_forklift
> MTV-49: Minimal hooks

- documentation/modules/rn-2.1.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1997023
Preview: https://deploy-preview-197--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-21_forklift
> BZ1997023: Ambiguous RHV resource name in UI (RN known issues)

- documentation/modules/rn-2.1.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2002617
Preview: https://deploy-preview-210--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-21_forklift
> BZ2002617: Delete snapshots after warm migration

- documentation/modules/common-attributes.adoc
> "v" with image name, 2.2 attributes

- _config.yml
- documentation/doc-Release_notes/master.adoc
- documentation/modules/rn-2.1.adoc
- documentation/modules/rn-2.2.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2018063
Add RN and QEMU guest agent known issue to RN
Preview: https://deploy-preview-227--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-22_forklift
> BZ2018063: QEMU guest agent - RN (all versions)

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/about-cold-warm-migration.adoc
- documentation/modules/canceling-migration-cli.adoc
- documentation/modules/changing-precopy-intervals-ui.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2012738
Previews:
https://deploy-preview-224--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#changing-precopy-intervals-ui_forklift
> BZ2012738: Changing precopy interval

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/migration-plan-options-ui.adoc
https://issues.redhat.com/browse/MTV-180
Added module about migration plan options.
Preview: https://deploy-preview-226--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migration-plan-options-ui_forklift
Ready for QE.
> MTV-180: Clone migration plan and other options

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/accessing-logs-cli.adoc
- documentation/modules/accessing-logs-ui.adoc
https://issues.redhat.com/browse/MTV-202
Preview: https://deploy-preview-242--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#downloading-logs-ui_forklift
> MTV-202: "Get logs" button

- documentation/modules/rn-2.2.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2020300
Preview: https://deploy-preview-243--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-22_forklift
Ready for QE.
> BZ2020300: Importer pod log unavailable after warm migration

- documentation/modules/upgrading-mtv-ui.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2024603
Preview: https://deploy-preview-253--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#upgrading-mtv-ui_forklift
> BZ2024603: forklift-ui pod ready during upgrade

- documentation/modules/rn-2.2.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2024178
Might be fixed before GA
Preview: https://deploy-preview-251--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-22_forklift
> BZ2024178: missing resource and log file error

- documentation/modules/accessing-logs-cli.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2029707
Preview: https://deploy-preview-257--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#accessing-logs-cli_forklift
Ready for QE.
> BZ2029707: VM name for must-gather

- _config.yml
- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/accessing-logs-cli.adoc
- documentation/modules/accessing-logs-ui.adoc
- documentation/modules/collected-logs-cr-info.adoc
- documentation/modules/mtv-workflow.adoc
- documentation/modules/virt-migration-workflow.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2025941
Preview: https://deploy-preview-256--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#collected-logs-cr-info_forklift
> BZ2025941: Targeted must-gather CRs and logs

- documentation/modules/rn-2.2.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2025989
Preview: https://deploy-preview-255--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-22_forklift
> BZ2025989: Critical issues do not block migration

- _config.yml
- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/about-rego-files.adoc
- documentation/modules/accessing-default-validation-rules.adoc
- documentation/modules/accessing-logs-cli.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/canceling-migration-cli.adoc
- documentation/modules/changing-precopy-intervals.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/creating-validation-rule.adoc
- documentation/modules/installing-mtv-operator.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/mtv-resources-and-services.adoc
- documentation/modules/obtaining-console-url.adoc
- documentation/modules/retrieving-validation-service-json.adoc
- documentation/modules/rn-2.0.adoc
- documentation/modules/uninstalling-mtv-cli.adoc
- documentation/modules/updating-validation-rules-version.adoc
- documentation/modules/upgrading-mtv-ui.adoc
https://issues.redhat.com/browse/MTV-205
Custom validation rules modules added.
NOTE: Remember to uncomment ifeval for TP notice in "about" module before merge.
Preview: https://deploy-preview-249--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#creating-custom-rules-for-validation-service
> MTV-205: custom validation rules

- documentation/modules/about-rego-files.adoc
- documentation/modules/rn-2.2.adoc
Preview: https://deploy-preview-262--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#new-features-and-enhancements-22_forklift
> Add custom validation rules to RN

- documentation/modules/rn-2.2.adoc
MTV 2.2
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2032014, which refers to BZ 2023764.
Preview: last item in https://deploy-preview-277--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-22_forklift (Immediately before the "Forklift 2.1" header)
> Add BZ#2023764 to known issues for MTV 2.2 Release notes

- documentation/modules/canceling-migration-cli.adoc
- documentation/modules/changing-precopy-intervals.adoc
- documentation/modules/upgrading-mtv-ui.adoc
Fixing redundant callouts like this:
> fix redundant callouts

- documentation/doc-Migration_Toolkit_for_Virtualization/docinfo.xml
- documentation/doc-Release_notes/docinfo.xml
Previous email address is now obsolete and has been replaced by ccs-mms-docs@redhat.com
> Updated MMS email address.

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
BZ2050710 Remove SHA 1 fingerprint of vCenter host prerequisite
MTV 2.3
https://bugzilla.redhat.com/show_bug.cgi?id=2050710
> BZ2050710 Remove SHA 1 fingerprint of vCenter host prerequisite for 2.3

- documentation/modules/compatibility-guidelines.adoc
MTV-262 Verify and update prerequisites as needed
MTV 2.3
https://issues.redhat.com/browse/MTV-262
> MTV-262 Verify and update prerequisites for MTV 2.3

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/vmware-prerequisites.adoc
Reverting https://github.com/konveyor/forklift-documentation/pull/282, which should not be part of the 2.2 branch.
> Bz2036928-revert Reverts changes that should not appear in the 2.2 branch.

- _config.yml
- documentation/modules/common-attributes.adoc
> 2.3-setup2 Updated OCP version

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-virt-provider.adoc
Reverts konveyor/forklift-documentation#292
> Revert "Split "Adding Providers" in the MTV user guide into source providers and destination providers "

- documentation/modules/creating-validation-rule.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/retrieving-validation-service-json.adoc
- documentation/modules/rhv-prerequisites.adoc
> 301cheerypick

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/creating-vddk-image.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
BZ2051655 vddkInitImage path is_part of Add VMware provider for MTV 2.3
MTV 2.3
https://bugzilla.redhat.com/show_bug.cgi?id=2051655
>  BZ2051655 vddkInitImage path is_part of Add VMware provider for MTV 2.3 

- documentation/modules/collected-logs-cr-info.adoc
Adding info based on upstream
MTV 2.3
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2070150
Preview: Last CR and last log in https://deploy-preview-312--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#collected-logs-cr-info_forklift
> BZ2070150_description of MTV hook logs

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/about-cold-warm-migration.adoc
- documentation/modules/creating-migration-plan.adoc
- documentation/modules/error-messages.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
https://issues.redhat.com/browse/MTV-289
Support for warm migration from RHV
> MTV-289 Support for warm migration from RHV

- documentation/modules/virt-migration-workflow.adoc
Bug fix
MTV 2.2
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2068879
Preview: Step 3 of https://deploy-preview-311--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#virt-migration-workflow_forklift
> MTV 2.2: Update step 3 of "Detailed migration workflow"

- documentation/doc-Release_notes/master.adoc
- documentation/modules/rn-2.3.adoc
https://issues.redhat.com/browse/MTV-286
MTV 2.3 Release notes
Preview:
https://deploy-preview-305--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#rn-23_forklift
> MTV-286: MTV 2.3 Release notes

- documentation/modules/upgrading-mtv-ui.adoc
> Red callouts

- documentation/modules/creating-vddk-image.adoc
2.2 BZ2050690 fix in Creating VDDK image section
MTV 2.2
https://bugzilla.redhat.com/show_bug.cgi?id=2050690
> 2.2 BZ2050690 fix in Creating VDDK image section

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/selecting-migration-network-for-vmware-source-provider.adoc
BZ2066328 Selection source provider network applies only to VMware
MTV 2.2
https://bugzilla.redhat.com/show_bug.cgi?id=2066328
> MTV 2.2: BZ2066328 Selection source provider network applies only to VMware

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/vmware-prerequisites.adoc
BZ2078187 Fix: VMware minimal privilege set is not included in MTV 2.3
https://bugzilla.redhat.com/show_bug.cgi?id=2078187
MTV 2.3
> BZ2078187 Fix: VMware minimal privilege set is not included in MTV 2.3

- documentation/modules/adding-source-provider.adoc
BZ2050735 MTV 2.2 Add the need for VSphere host admin rights
MTV 2.2
https://bugzilla.redhat.com/show_bug.cgi?id=2050735
Preview:
https://deploy-preview-328--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#adding-source-provider_forklift
> BZ2050735 MTV 2.2 Add the need for VSphere host admin rights

- documentation/modules/rn-2.3.adoc
MTV 2.3.2
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2103938 by removing two issues that were resolved in 2.3.2 from the Known issues section. 
Preview: https://deploy-preview-331--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-23_forklift [Items are not there]
> BZ#2103938 -- Remove resolved issues from list of known issues

- documentation/modules/rn-2.3.adoc
MTV 2.3.2
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2103945 by adding link to first known issue.
Preview: https://deploy-preview-330--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-23_forklift
> BZ#2103945: Add link to known issue

- documentation/modules/creating-validation-rule.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/retrieving-validation-service-json.adoc
- documentation/modules/rhv-prerequisites.adoc
https://github.com/konveyor/forklift-documentation/pull/326 for MTV 2.2
> BZ#2078360 for MTV 2.2

- documentation/modules/rn-2.3.adoc
> Release notes 2.3.3

- documentation/modules/rn-2.3.adoc
Redo of PR 331, which was merged however did neither appeared in the sync'ed version nor was contained in "main" after multiple rebasings...
> Re merge PR 331

- documentation/modules/rn-2.3.adoc
MTV 2.3.3 Release notes
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2127197 by removing BZ2055201 from known issues.
> Removes BZ2055201 from known issues in MTV 2.3 release notes

- documentation/modules/virt-migration-workflow.adoc
Signed-off-by: Avital Pinnick <apinnick@redhat.com>
> fix bad line breaks

- documentation/modules/compatibility-guidelines.adoc
- documentation/modules/installing-mtv-operator.adoc
MTV-2.3.3
Resolves - https://bugzilla.redhat.com/show_bug.cgi?id=2130458
Preview isn't currently available. 
Updates are in - Chapter 2 - Table 2.5 and Chapter 3 - Prerequisites.
> BZ-2130458 - Prerequisite Updates 

- documentation/modules/network-prerequisites.adoc
Resolves: https://issues.redhat.com/browse/MTV-423
MTV 2.3.0
> MTV-423: Document_fix

- documentation/modules/retrieving-validation-service-json.adoc
MTV 4.2
Resolves https://issues.redhat.com/browse/MTV-470 by adding 2 steps to the procedure and making additional changes suggested in the PR.
Preview: http://file.emea.redhat.com/rhoch/invent_service_json/html-single/#retrieving-validation-service-json_mtv [steps 1-6]
> Invent service json

- documentation/modules/increasing-nfc-memory-vmware-host.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
Corrected two small typos
1. modified:   documentation/modules/increasing-nfc-memory-vmware-host.adoc
Line 9 -  **Otherwise,the migration** changed to **Otherwise, the migration**
2. modified:   documentation/modules/migrating-virtual-machines-cli.adoc
Line 239 - **migation** plan changed to **migration plan**
> MTV-509: typos corrected aa

- documentation/modules/creating-network-mapping.adoc
MTV 4.2
https://github.com/kubev2v/forklift-documentation/pull/357 updated the description of how to create Network Maps in the UI.
This PR makes a small change to the prerequisites of the section.
> cleanup: networkMapping

- documentation/modules/mtv-resources-and-services.adoc
- documentation/modules/mtv-workflow.adoc
- documentation/modules/virt-migration-workflow.adoc
In 2.4.0 we added the volume populator flow to the migrations as well re-ordering the migration flow.
> Add populator flow

- documentation/doc-Release_notes/master.adoc
- documentation/modules/rn-2.4.adoc
@ahadas @qiyuann @mavital 
Adding a new clean version of the MTV 2.4.0 release notes without junk files and typos corrected. 
The other ones are such a mess, I thought it's best to start from scratch.
Please, could you do the necessary review? 
Thanks
> aa/MTV-475: adding 2.4.0 release notes

- documentation/modules/canceling-migration-ui.adoc
- documentation/modules/common-attributes.adoc
MTV 2.4
Fixes document abstract and makes other minor change for consistency.
> fixes abstract

- documentation/modules/upgrading-mtv-ui.adoc
MTV 2.4
Partially resolves https://issues.redhat.com/browse/MTV-510 by updating "Chapter 7. Upgrading the Migration Toolkit for Virtualization" of the user guide.
Preview: http://file.emea.redhat.com/rhoch/cleanup_upgrade/html-single/#upgrading-mtv-ui_mtv
> Cleanup upgrade

- documentation/modules/using-must-gather.adoc
> Fixes callout

- documentation/modules/rn-2.4.adoc
Fixing errors in attributes in release notes
> Fixing attribute errors in release notes for MTV 2.4.1

- documentation/modules/rn-2.4.adoc
Changing attribute - *{scp}* to *{osp}*
> Adding another fix changing attribute scp to osp

- documentation/modules/common-attributes.adoc
- documentation/modules/creating-vddk-image.adoc
- documentation/modules/rn-2.4.adoc
Adding release notes and attributes update for MTV 2.4.2 release notes
> MTV-614: adding release notes and attribute update for 2.4.2

- documentation/modules/rn-2.4.adoc
2.4.2
[no jira] Makes minor changes in the release notes for MTV 2.4.2. 
Preview: https://file.emea.redhat.com/rhoch/rn_mods/html-single/#known-issues-24_release-notes, sections 1.3 and 1.4
> Minor changes to MTV 2.4.2 release notes

- documentation/modules/common-attributes.adoc
@ahadas @qiyuann 
Should I update the **Compatibility Guidelines**:
forklift-documentation/documentation/modules/compatibility-guidelines.adoc:
|===
|{project-full} |{ocp} |{virt} |VMware vSphere |{rhv-full}|OpenStack
|2.4.0 |4.11 or later |4.11 or later |6.5 or later |4.4.9 or later|16.1 or later
|===
> Updating attributes template

- documentation/modules/compatibility-guidelines.adoc
MTV 2.5.0
Updates https://access.redhat.com/documentation/en-us/migration_toolkit_for_virtualization/2.5/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#compatibility-guidelines_mtv for MTV version 2.5.0 
Preview: https://file.emea.redhat.com/rhoch/compat/html-single/#compatibility-guidelines_mtv
> Compatibility guidelines

- documentation/modules/vmware-prerequisites.adoc
@ahadas - rather than a note, I thought it would be best to include at the very top of this section. 
I hope this is ok.
> Updating VMWare pre-requisites to include important note

- documentation/modules/compatibility-guidelines.adoc
[MTV-726](https://issues.redhat.com/browse/MTV-726)
Changed compatibility guide module
> MTV-726: Changed RHV version to 4.4 SP1 or later

- documentation/modules/rn-2.5.adoc
@ahadas - please can you list what you want covering in the release notes
I thought it best to give you access so you can add notes
Thanks
> MTV-674: release notes for MTV 2.5.1

- documentation/modules/compatibility-guidelines.adoc
@ahadas - please can I get a LGTM. I will merge and review later today
Thanks
> Updated .Migration from {rhv-full} 4.3

- documentation/modules/rn-2.4.adoc
* [MTV-789](https://issues.redhat.com/browse/MTV-789): Release notes for MTV 2.4.3
> MTV-789: Release Notes for MTV 2.4.3

- documentation/modules/rn-2.5.adoc
* [MTV-815](https://issues.redhat.com/browse/MTV-815)
* [Migration_Toolkit_for_Virtualization-2.5-Release_notes-en-US.pdf](https://github.com/kubev2v/forklift-documentation/files/13467280/Migration_Toolkit_for_Virtualization-2.5-Release_notes-en-US.pdf)
> MTV-815: Release notes for MTV 2.5.3

- documentation/modules/common-attributes.adoc
- documentation/modules/compatibility-guidelines.adoc
* [MTV-854](https://issues.redhat.com/browse/MTV-854)
* Updating Attributes to 2.5.4
* Updating Software compatibility guidelines to include attribute 
* Adding OpenShift Operator Life Cycles - I think this is an important link so I adding it to the documentation unless you have any major concerns. I have been asked twice about this link, for MTA and OADP respectively
> MTV-854: Attributes for MTV-2.5.4

- documentation/modules/compatibility-guidelines.adoc
MTV Version 2.5.4
Resolves - https://issues.redhat.com/browse/MTV-839
Deploy preview - file:///home/cwisemon/repos/forklift-documentation/documentation/doc-Migration_Toolkit_for_Virtualization/build/tmp/en-US/html-single/index.html#compatibility-guidelines_mtv
> MTV 839 Enabling deployment on OKE

- documentation/modules/migrating-virtual-machines-cli.adoc
Adds comma to callout 10 of step 1 of the CLI instructions.
> Adding comma

- documentation/modules/common-attributes.adoc
* [MTV-962](https://issues.redhat.com/browse/MTV-962)
No preview
> Mtv 962 mtv 2 5 6 common attributes

- documentation/modules/common-attributes.adoc
* https://issues.redhat.com/browse/MTV-814
No preview
> MTV 2.6 common attributes

- documentation/modules/adding-source-provider.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-942 and https://issues.redhat.com/browse/MTV-553 by adding vSphere endpoint options to the procedure for creating a vSphere source provider using the UI.
> Add vSphere endpoint options

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/creating-migration-quick-plan-existing-source.adoc
- documentation/modules/creating-migration-quick-plan-vm.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-807 by describing how to create migration plans in MTV 2.6.0
Preview:
https://file.emea.redhat.com/rhoch/quick_plan/html-single/#creating-migration-plans-ui
> Quick Plan

- documentation/modules/about-hook-crs-for-migration-plans-api.adoc
- documentation/modules/adding-hook-crs-to-migration-plans-api.adoc
MTV 2.6.0
Resolves https://issues.redhat.com/browse/MTV-448 by adding a note about usage with PreHooks.
Preview: https://file.emea.redhat.com/rhoch/prehook_addition/html-single/#adding-hooks-migration-plan-using-api
> Additional information about working with PreHooks

- documentation/modules/rn-2.6.adoc
* [MTV 2.6.0 Release Notes](https://issues.redhat.com/browse/MTV-813)
> MTV-813: MTV 2.6.0: release notes

- documentation/modules/configuring-mtv-operator.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-1103 for MTV 2.5.x
> Fix max_vm_inflight setting name for MTV 2.5

- documentation/modules/common-attributes.adoc
- documentation/modules/compatibility-guidelines.adoc
- documentation/modules/creating-vddk-image.adoc
MTV 2.6.1
Resolves https://issues.redhat.com/browse/MTV-1094 by changing document attributes where needed.
> Attributes for MTV 2.6.1

- documentation/modules/rn-2.6.adoc
MTV 2.6.1
Resolves https://issues.redhat.com/browse/MTV-1093 by adding release note items for MTV 2.6.1. 
Preview: https://file.emea.redhat.com/rhoch/mtv_261_rn/html-single/#resolved-issues-26_release-notes [first three items]
> Release notes for MTV 2.6.1

- documentation/modules/compatibility-guidelines.adoc
* [MTV-1158](https://issues.redhat.com/browse/MTV-1158)
> MTV-1158: Error in compatability guidelines

- documentation/modules/common-attributes.adoc
* [MTV-1143](https://issues.redhat.com/browse/MTV-1143)
Updated z stream attributes to 2.6.3
> mtv-1143 updated attributes to 2.6.3

- documentation/modules/rn-2.6.adoc
MTV 2.6.3
Resolves https://issues.redhat.com/browse/MTV-1142 by creating release notes for MTV 2.6.3.
Previews:
- https://file.emea.redhat.com/rhoch/263_rn/html-single/#new-features-and-enhancements-26_release-notes [First 4 items in New features]
- https://file.emea.redhat.com/rhoch/263_rn/html-single/#resolved-issues-26_release-notes [First 6 items in Resolved issues]
> Release notes for MTV 2.6.3

- documentation/modules/rn-2.6.adoc
Fixes formatting error in MTV 2.6.3 Release notes
Preview: https://file.emea.redhat.com/rhoch/263rn_fix_formatting/html-single/#new-features-and-enhancements-26_release-notes [2nd item]
> Fixes formatting error in MTV 2.6.3 Release notes

- documentation/modules/rn-2.6.adoc
* [MTV-1279](https://issues.redhat.com/browse/MTV-1279)
* [ New features and enhancements 2.6.4](https://anarnold97.github.io/MTA-Preview/MTV/mtv-2-6-4-rn.html#new-features-and-enhancements-26-4_release-notes)
* [2.6.4 resolved issues](https://anarnold97.github.io/MTA-Preview/MTV/mtv-2-6-4-rn.html#resolved-issues-26-4_release-notes)
* [2.6 Known issues](https://anarnold97.github.io/MTA-Preview/MTV/mtv-2-6-4-rn.html#known-issues-26_release-notes)
the release notes need to cover the following changes in 2.6.4:
* [MTV-1286](https://issues.redhat.com/browse/MTV-1286) - documented as a resolved issue
* [MTV-1299](https://issues.redhat.com/browse/MTV-1299) - documented as a resolved issue
* [MTV-1325](https://issues.redhat.com/browse/MTV-1325) - documented as a resolved issue
* …
> MTV-1279 - MTV 2.6.4 release notes

- documentation/modules/common-attributes.adoc
* [MTV-1280](https://issues.redhat.com/browse/MTV-1280)
Updated attribute to 2.6.4 
Please can I double-check the OCP version
> MTV-1280: Attributes for MTV 2.6.4

- documentation/modules/common-attributes.adoc
* [MTV-1359](https://issues.redhat.com/browse/MTV-1359)
> WIP - MTV-1359: Attributes update for MTV 2.6.5

- documentation/modules/rn-2.6.adoc
* [MTV-1358](https://issues.redhat.com/browse/MTV-1358)
* [Resolved issues 2.6.5](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-6-5.html#resolved-issues-26-5_release-notes)
* [Updated known issues](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-6-5.html#known-issues-26_release-notes)
> WIP - MTV-1358: Release Notes for MTV 2.6.5

- documentation/modules/rn-2.6.adoc
* [MTV-1385](https://issues.redhat.com/browse/MTV-1385)
* [MTV 2.6.6 release notes](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-6-6.html)
* [Resolved issues 2.6.6](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-6-6.html#resolved-issues-26-6_release-notes)
* [Known issues](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-6-6.html#known-issues-26_release-notes)
> MTV-1385: Release Notes for MTV 2.6.6

- documentation/modules/common-attributes.adoc
* [MTV-1386](https://issues.redhat.com/browse/MTV-1386)
Change:
```
project-z-version: 2.6.6
```
> MTV-1386: Attributes update for MTV 2.6.6

- documentation/modules/common-attributes.adoc
- documentation/modules/rn-2.6.adoc
* [MTV-1446](https://issues.redhat.com/browse/MTV-1446) - Release notes
* [MTV-1447](https://issues.redhat.com/browse/MTV-1447) - Attributes
* [MTV 2.6.7 resolved issues](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-6-7.html#resolved-issues-26-7_release-notes)
> MTV-1446: MTV 2.6.7 release notes

- documentation/doc-Release_notes/master.adoc
- documentation/modules/known-issues-2-7.adoc
- documentation/modules/new-features-and-enhancements-2-7.adoc
- documentation/modules/rn-2.7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
- documentation/modules/technical-changes-2-7.adoc
* [MTV-1096](https://issues.redhat.com/browse/MTV-1096)
* [Release Notes MTV 2.7.0](https://anarnold97.github.io/MTA-Preview/MTV/rn-27.html)
> MTV-1096: Release Notes for MTV 2.7.0

- documentation/modules/about-cold-warm-migration.adoc
- documentation/modules/snip_cold-warm-comparison-table.adoc
MTV 2.7.0
Resolves https://issues.redhat.com/browse/MTV-1254 by adding more information about the differences between cold and warm migrations for MTV 2.7.0.
Preview: https://file.corp.redhat.com/rhoch/warm_col/html-single/#warm-migration-versus-cold-migration [section 1.1.3]
> Additions to cold vs warm migration

- documentation/modules/adding-source-provider.adoc
* [MTV-1308](https://issues.redhat.com/browse/MTV-1308)
* [4.4.1.1. Adding a VMware vSphere source provider](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1308.html#adding-source-providers)
> MTV-1308: VDDK is mentioned as strongly recommended but in many situations, when not installed, migration fails

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/snip_secure_boot_issue.adoc
- documentation/modules/source-vm-prerequisites.adoc
* [MTV-1548](https://issues.redhat.com/browse/MTV-1548)
Created a snippet.
Added this snippet to the *2.7 Known Issues* and also added to the Source virtual machine prerequisites.
> MTV-1548: VMs with Secure Boot cannot be migrated automatically

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1554](https://issues.redhat.com/browse/MTV-1554)
* [MTV 2.7.2 release notes](https://anarnold97.github.io/MTA-Preview/MTV/2.7.2-rn.html)
> MTV-1554: release notes for MTV 2.7.2

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1604](https://issues.redhat.com/browse/MTV-1604)
* [MTV 2.7.3 resolved issue](https://anarnold97.github.io/MTA-Preview/MTV/2-7-3-rn.html#resolved-issues-2-7-3_release-notes)
> MTV-1604: Release Notes for MTV 2.7.3

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/snip_measured_boot_windows_vm.adoc
- documentation/modules/source-vm-prerequisites.adoc
* [MTV-1621](https://issues.redhat.com/browse/MTV-1621)
* [MTV 2.7 release notes](https://anarnold97.github.io/MTA-Preview/MTV/mtv-1621-rn.html#known-issues-2-7_release-notes)
* [MTV 2.7 docs](https://anarnold97.github.io/MTA-Preview/MTV/mtv-1621-doc.html#source-vm-prerequisites_mtv)
| Docs | Release Notes |
| ------- | ------------- |
| ![image](https://github.com/user-attachments/assets/35b62464-40ef-41e8-a42c-6606ed186caf)   | ![image](https://github.com/user-attachments/assets/81a044a4-3d53-4407-826b-0f8ec344abbb) |
> MTV-1621: Measured Boot Windows VMs

- documentation/modules/common-attributes.adoc
* [MTV-1605](https://issues.redhat.com/browse/MTV-1605)
* [Compatibility guide](https://anarnold97.github.io/MTA-Preview/MTV/2-7-3-attributes.html#compatibility-guidelines_mtv)
> MTV-1605: Attributes update for MTV 2.7.3

- documentation/modules/running-migration-plan.adoc
* [MTV-1683](https://issues.redhat.com/browse/MTV-1683)
* [4.6. Running a migration plan](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1683-vMotion#running-migration-plan_mtv)
| v1 | v2 |
| ---------| -------- |
| ![image](https://github.com/user-attachments/assets/5b94256d-466d-48f2-8303-7d31d0bbf3de)   | ![image](https://github.com/user-attachments/assets/5a768f78-8c55-447f-9bd0-a3be1712dc1c)  |
> MTV-1683: vMotion should be disabled for VMs getting imported

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1649](https://issues.redhat.com/browse/MTV-1649)
* [Release notes MTV 2.7.4: Resolved issues](https://anarnold97.github.io/MTA-Preview/MTV/mtv-2-7-4-rn.html#resolved-issues-2-7-4_release-notes)
* [Known issues](https://anarnold97.github.io/MTA-Preview/MTV/mtv-2-7-4-rn.html#known-issues-2-7_release-notes)
> MTV-1649: Release Notes for MTV 2.7.4

- documentation/modules/mtv-changelog-2-7.adoc
- documentation/modules/mtv-selected-packages-2-7.adoc
* [MTV-1691](https://issues.redhat.com/browse/MTV-1691)
* [1.1.1. MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/274-packages.html#mtv-selected-packages-2-7_release-notes)
* [1.5.1. MTV 2.7 packages](https://anarnold97.github.io/MTA-Preview/MTV/274-packages.html#mtv-container-packages_release-notes)
> MTV-1691: update packages for 2.7.4

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1709](https://issues.redhat.com/browse/MTV-1709)
* [1.3.1. Resolved issues 2.7.5](https://anarnold97.github.io/MTA-Preview/MTV/mtv-rn-2-7-5.html#resolved-issues-2-7-5_release-notes)
* [1.4. Known issues](https://anarnold97.github.io/MTA-Preview/MTV/mtv-rn-2-7-5.html#known-issues-2-7_release-notes)
> MTV-1709: Release Notes for MTV 2.7.5

- documentation/modules/common-attributes.adoc
* [MTV-1708](https://issues.redhat.com/browse/MTV-1708)
> MTV-1708: Attributes update for MTV 2.7.5

- documentation/modules/mtv-selected-packages-2-7.adoc
* [MTV 2.7.5 release notes](https://anarnold97.github.io/MTA-Preview/MTV/mtv-packages.html#mtv-selected-packages-2-7_release-notes)
> Removing packages list from MTV 2.7.5 docs

- documentation/modules/mtv-selected-packages-2-7.adoc
* [MTV-1751](https://issues.redhat.com/browse/MTV-1751)
* [MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/2-7-6-packages.html#mtv-selected-packages-2-7_release-notes)
> MTV-1770: Updating packages for 2.7.6

- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1751](https://issues.redhat.com/browse/MTV-1751)
* [ Resolved issues 2.7.6](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-7-6.html#resolved-issues-2-7-6_release-notes)
> MTV-1751: Release Notes for MTV 2.7.6

- documentation/modules/common-attributes.adoc
* [MTV-1750](https://issues.redhat.com/browse/MTV-1750)
> MTV-1750: Attributes update for MTV 2.7.6

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/mtv-aio-buffer.adoc
* [MTV-1722](https://issues.redhat.com/browse/MTV-1722)
* [Increasing asynchronous I/O (AIO) sizes and buffer counts for NBD transport mode](https://anarnold97.github.io/MTA-Preview/MTV/aio-buffer.html#mtv-aio-buffer_mtv)
> MTV-1722: AIO buffer performance

- documentation/modules/mtv-ui.adoc
* [MTV-1795](https://issues.redhat.com/browse/MTV-1795)
* [4.1. The MTV user interface](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1795.html#mtv-ui_mtv)
> MTV-1795: Typo in the MTV UI guide

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/vddk-validator-containers.adoc
* [MTV-1800](https://issues.redhat.com/browse/MTV-1800)
As Martin put this for 2.7.7, I presume it needs to be done ASAP.
* [2.7.3. VDDK validator containers need requests and limits](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1800-VDDK-validator#vddk-validator-containers_mtv)
> MTV-1800: VDDK validator

- documentation/modules/common-attributes.adoc
* [MTV-1784](https://issues.redhat.com/browse/MTV-1784)
* [2.9. Software compatibility guidelines](https://anarnold97.github.io/MTA-Preview/MTV/attributes-2.7.7.html#compatibility-guidelines_mtv)
> MTV-1784: Attributes update for MTV 2.7.7

- documentation/doc-Release_notes/master.adoc
- documentation/modules/mtv-selected-packages-2-7.adoc
* [1.1.1. MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/MTV-2-7-7-packages.html#mtv-selected-packages-2-7_release-notes)
> MTV 2.7.7 packages update

- documentation/modules/snip_dualboot_vm.adoc
Migration of dual-boot VMs is best effort, let's try to capture this in words.
> MTV-1877 | Clarification of dual boot support

- documentation/modules/mtv-selected-packages-2-7.adoc
* [MTV-1899](https://issues.redhat.com/browse/MTV-1899)
* [1.1.1. MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/2.7.8-packages.html#mtv-selected-packages-2-7_release-notes)
> MTV-1899: Updated selected packages for MTV 2.7.8

- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1932](https://issues.redhat.com/browse/MTV-1932)
* [1.3.1. Resolved issues 2.7.9](https://anarnold97.github.io/MTA-Preview/MTV/rn-2.9.html#resolved-issues-2-7-9_release-notes)
> MTV-1932: Release Notes for MTV 2.7.9

- documentation/modules/mtv-selected-packages-2-7.adoc
* [MTV-1933](https://issues.redhat.com/browse/MTV-1933)
* [Selected packages 2.7.9](https://anarnold97.github.io/MTA-Preview/MTV/2-7-9-packages.html#mtv-selected-packages-2-7_release-notes)
> MTV-1933: Updating Packages for MTV 2.7.9

- documentation/modules/common-attributes.adoc
* [MTV-1931](https://issues.redhat.com/browse/MTV-1931)
> MTV-1931: Attributes updates for MTV 2.7.9

- documentation/modules/mtv-performance-recommendation.adoc
MTV 2.7.10
Resolves https://issues.redhat.com/browse/MTV-1897 by adding warm migration recommendations to chapter 9 of the MYV user guide. 
Previews: 
- https://file.corp.redhat.com/rhoch/warm_mig_recs/html-single/#mtv-warm-migration-recommendations_mtv
- https://file.corp.redhat.com/rhoch/warm_mig_recs/html-single/#mtv-performance-max-values-warm_mtv
> MTV-1897 Update performance recommendations for warm migration

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/creating-migration-plan-2-6-3.adoc
Reverts kubev2v/forklift-documentation#630
> Revert "MTV-1433 UI plans by provider - FIXED"

- documentation/modules/common-attributes.adoc
* [MTV-1946](https://issues.redhat.com/browse/MTV-1946)
> MTV-1946 Attributes Update for 2.7.10

- documentation/doc-Release_notes/master.adoc
- documentation/modules/mtv-selected-packages-2-7.adoc
* [MTV-2045](https://issues.redhat.com/browse/MTV-2045)
* [2.1. MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/2-7-10-packages.html#mtv-selected-packages-2-7_release-notes)
> MTV-2045: Updating packages for 2.7.10

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/creating-migration-plan-2-8.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/ostack-app-cred-auth.adoc
- documentation/modules/ostack-token-auth.adoc
- documentation/modules/selecting-migration-network-for-virt-provider.adoc
- documentation/modules/selecting-migration-network-for-vmware-source-provider.adoc
- documentation/modules/snip-mtu-value.adoc
* [MTV-1433](https://issues.redhat.com/browse/MTV-1433)
* [MTV docs](https://anarnold97.github.io/MTA-Preview/MTV/fixes.html)
> MTV-1433 Fixes

- documentation/modules/known-issues-2-7.adoc
* [MTV-2107](https://issues.redhat.com/browse/MTV-2107)
> MTV-2107: Adding RHEL-32099 to release notes

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/creating-migration-plan-2-8.adoc
- documentation/modules/uninstalling-mtv-cli.adoc
- documentation/modules/vddk-validator-containers.adoc
@RichardHoch - I do not think the taxonomy works particularly well for providers being introduced at `level 4`
i would move them up to `level 2` or to `level 3`
In this preview, i have moved them up to `level 2`. *WDYT* ?
* [MTV docs](https://anarnold97.github.io/MTA-Preview/MTV/taxonomy.html)
> New Taxonomy for MTV Providers

- documentation/modules/mtv-selected-packages-2-7.adoc
* [MTV-2169](https://issues.redhat.com/browse/MTV-2169)
* [Packages 2.7.11](https://anarnold97.github.io/MTA-Preview/packages.html#mtv-selected-packages-2-7_release-notes)
> MTV-2169: Updating-packages for 2.7.11

- documentation/modules/mtv-aio-buffer.adoc
- documentation/modules/rn-2.6.adoc
- documentation/modules/snip_dualboot_vm.adoc
- documentation/modules/snip_vmware-permissions.adoc
* [MTV-2221](https://issues.redhat.com/browse/MTV-2221)
> MTV-2221: Remove titles for admonition

- documentation/modules/adding-source-provider.adoc
- documentation/modules/snip-vsan.adoc
- documentation/modules/vmware-prerequisites.adoc
* [MTV-2203](https://issues.redhat.com/browse/MTV-2203)
* [3.7. VMware prerequisites](https://anarnold97.github.io/MTA-Preview/MTV/mtv-vsan.html#vmware-prerequisites_mtv)
* [6.1. Adding a VMware vSphere source provider](https://anarnold97.github.io/MTA-Preview/MTV/mtv-vsan.html#adding-source-provider_vmware)
> MTV-2203: Document VDDK as a hard requirement for vSAN backed VM migrations

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/doc-Release_notes/master.adoc
- documentation/modules/vmware-prerequisites.adoc
* [MTV-2288](https://issues.redhat.com/browse/MTV-2288)
* [Preview of changes](https://anarnold97.github.io/MTA-Preview/MTV/discrete-headers.html)
> MTV-2288 : Removing discrete headers

- documentation/doc-Release_notes/master.adoc
- documentation/modules/known-issues-2-8.adoc
- documentation/modules/mtv-selected-packages-2-8.adoc
- documentation/modules/new-features-and-enhancements-2-8.adoc
- documentation/modules/rn-2.8.adoc
- documentation/modules/rn-28-resolved-issues.adoc
- documentation/modules/technical-changes-2-8.adoc
* [MTV-2033 Release Notes 2.8.0](https://issues.redhat.com/browse/MTV-2033)
* MTV 2.8.0
* [MTV 2.8.0 Release Notes](https://file.corp.redhat.com/pkylasam/mtv-2033-rn/html-single/)
> To be merged 2.8.0 - MTV-2033 RN 2.8.0

- documentation/modules/mtv-selected-packages-2-8.adoc
* [MTV-2034](https://issues.redhat.com/browse/MTV-2034)
* [Preview of table](https://github.com/kubev2v/forklift-documentation/blob/3111388209a1fd45cc9bc99e6efb9b0afe2e36e0/documentation/modules/mtv-selected-packages-2-8.adoc) - module not included in docs. It will be included as part of Prabha's release notes.
> To be merged for 2.8.0 - MTV-2034: Packages for MTV 2.8.0

- documentation/modules/known-issues-2-8.adoc
- documentation/modules/new-features-and-enhancements-2-8.adoc
- documentation/modules/rn-2.8.adoc
- documentation/modules/rn-28-resolved-issues.adoc
MTV 2.8.1
Resolves https://issues.redhat.com/browse/MTV-2341 by adding release notes for MTV 2.8.1.
Previews:
- https://file.corp.redhat.com/rhoch/MTV_281_release_notes/html-single/#new-features-and-enhancements-2-8_release-notes [last 2 items]
- https://file.corp.redhat.com/rhoch/MTV_281_release_notes/html-single/#resolved-issues-2-8-1_release-notes [all]
- https://file.corp.redhat.com/rhoch/MTV_281_release_notes/html-single/#known-issues-2-8_release-notes [last item]
> TO BE MERGED FOR MTV 2.8.1: MTV 2.8.1 Release notes

- documentation/modules/common-attributes.adoc
Resolves https://issues.redhat.com/browse/MTV-2342 by updating common-attributes.adoc for MTV 2.8.1.
Previews:
- https://file.corp.redhat.com/rhoch/MTV_281_attributes/html-single/#installing-mtv-operator_cli [step 3]
- https://file.corp.redhat.com/rhoch/MTV_281_attributes/html-single/#using-must-gather_mtv [steps 2 and 3]
- https://file.corp.redhat.com/rhoch/MTV_281_attributes/html-single/#accessing-logs-cli_mtv [steps 2 and 3]
> TO BE MERGED FOR MTV 2.8.1: Attributes for MTV 2.8.1

- documentation/doc-Release_notes/master.adoc
- documentation/modules/mtv-selected-packages-2-8.adoc
* [MTV-2390](https://issues.redhat.com/browse/MTV-2390) - Adding packages for MTV 2.8.1
* [2.1. MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/packages-281.html#mtv-selected-packages-2-8_release-notes)
> MTV-2390: Packages for MTV 2.8.1

- documentation/modules/mtv-selected-packages-2-8.adoc
* [MTV-2396](https://issues.redhat.com/browse/MTV-2396)
* [2.1. MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/mtv-282-packages.html#mtv-selected-packages-2-8_release-notes)
> To be merged for 2.8.2 - MTV-2396: MTV 2.8.2 packages update

- documentation/modules/common-attributes.adoc
MTV 2.8.2
Resolves https://issues.redhat.com/browse/MTV-2398 by updating the attributes for MTV 2.8.2.
Previews: 
- https://file.corp.redhat.com/rhoch/MTV_282_attributes/html-single/#installing-mtv-operator_cli [step 3]
- https://file.corp.redhat.com/rhoch/MTV_282_attributes/html-single/#using-must-gather_mtv [steps 2 and 3]
- https://file.corp.redhat.com/rhoch/MTV_282_attributes/html-single/#accessing-logs-cli_mtv [steps 2 and 3]
> TO BE MERGED FOR MTV 2.8.2: Attributes for MTV 2.8.2

- documentation/modules/common-attributes.adoc
- documentation/modules/rn-27-resolved-issues.adoc
MTV 2.7.12
Previews:
- https://file.corp.redhat.com/rhoch/2_7_12_attributes/html-single/#installing-mtv-operator_cli [step 3]
- https://file.corp.redhat.com/rhoch/2_7_12_attributes/html-single/#using-must-gather_mtv [steps 2 and 3]
- https://file.corp.redhat.com/rhoch/2_7_12_attributes/html-single/#accessing-logs-cli_mtv [steps 2 and 3]
- https://file.corp.redhat.com/rhoch/2_7_12_release_notes/html-single/#resolved-issues-2-7-12_release-notes [only item]
> MTV 2.7.12 attributes

- documentation/modules/adding-source-provider.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/snip_no-nvme.adoc
* [MTV-2443](https://issues.redhat.com/browse/MTV-2443)
Cloned from [PR](https://github.com/kubev2v/forklift-documentation/pull/688)
* MTV 2.8.3
> MTV-2443: MTV does not support migrating VMware NVMe disks

- documentation/modules/mtv-selected-packages-2-8.adoc
* [MTV-2494](https://issues.redhat.com/browse/MTV-2494)
* [2.1. MTV selected packages](https://anarnold97.github.io/MTA-Preview/MTV/packages2-8-3.html#mtv-selected-packages-2-8_release-notes)
> MTV-2494: MTV packages 2.8.3

- documentation/modules/mtv-performance-recommendation.adoc
* [MTV-2391](https://issues.redhat.com/browse/MTV-2391)
Fixing merge conflict - https://github.com/kubev2v/forklift-documentation/pull/683
> MTV-2391: Update performance recommendations for warm migration

- documentation/modules/rn-28-resolved-issues.adoc
MTV 2.8.4
Resolves https://issues.redhat.com/browse/MTV-2504 by adding release notes for MTV 2.8.4.
Preview: https://file.corp.redhat.com/rhoch/MTV-2505-2-8-4-release-notes/html-single/#resolved-issues-2-8-4_release-notes [1 item]
> HOLD FOR MTV 2.8.4: MTV 2.8.4 Release notes

- documentation/modules/canceling-migration-cli.adoc
* [MTV-2302](https://issues.redhat.com/browse/MTV-2302) 
|One result returned from a search:|
| ------------------------------------------------- |
| ![image](https://github.com/user-attachments/assets/3fd513b8-6040-47d7-9186-b7ef48ecbfe3) |
> 2.8 - MTV-2302: Fix formats as the format for the vms list is wrong

- documentation/modules/snip-vsan.adoc
- documentation/modules/snip_vmware-windows-vss.adoc
- documentation/modules/source-vm-prerequisites.adoc
- documentation/modules/vmware-prerequisites.adoc
* [MTV-2304](https://issues.redhat.com/browse/MTV-2304)
* [3.4. Source virtual machine prerequisites](https://anarnold97.github.io/MTA-Preview/MTV/28-vss.html#source-vm-prerequisites_mtv)
* [3.7. VMware prerequisites](https://anarnold97.github.io/MTA-Preview/MTV/28-vss.html#vmware-prerequisites_mtv)
| Admonition |
| ----------------- |
|![image](https://github.com/user-attachments/assets/197f9802-7467-455c-bda2-a9a6197f995c)|
> 2.8 - MTV-2304: MTV Documentation missing information regarding Windows OS

- documentation/modules/creating-migration-plan-2-8.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
* [MTV-2573](https://issues.redhat.com/browse/MTV-2573)
> MTV-2573: .VmName spelled incorrectly in MTV Docs

- documentation/modules/known-issues-2-8.adoc
- documentation/modules/rn-28-resolved-issues.adoc
MTV 2.8.5
Resolves https://issues.redhat.com/browse/MTV-2594 adding release notes for MTV 2.8.5.
- Preview: https://file.corp.redhat.com/rhoch/MTV-2594-MTV-2_8_5-release-notes/html-single/#resolved-issues-2-8-5_release-notes [1 item]
- https://file.corp.redhat.com/rhoch/MTV-2594-MTV-2_8_5-release-notes/html-single/#known-issues-2-8_release-notes [last 2 items]
> MTV 2.8.5: MTV-2594-MTV-2_8_5-release-notes

- documentation/doc-Release_notes/master.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/rn-2-9-1-resolved-issues.adoc
* [MTV-2830](https://issues.redhat.com/browse/MTV-2830)
* 2.9.1
* [Resolved issues 2.9.1](https://pkylas007.github.io/Preview/MTV/mtv-2830/index.html#resolved-issues-2-9-1_release-notes)
> MTV-2830 Release Notes for 2.9.1

- documentation/doc-Release_notes/master.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/rn-2-9-2-resolved-issues.adoc
* [MTV-3099](https://issues.redhat.com/browse/MTV-3099)
> MTV-3099: Release Notes for MTV 2.9.2

- documentation/doc-Release_notes/master.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/rn-2-9-3-resolved-issues.adoc
* [MTV-3148](https://issues.redhat.com/browse/MTV-3148)
> MTV-3148: Release Notes and Attributes for MTV 2.9.3

- documentation/doc-Release_notes/master.adoc
https://issues.redhat.com/browse/MTV-2765
> MTV-2765 remove inclusive module release notes

- documentation/modules/common-attributes.adoc
- documentation/modules/rn-2-9-4-resolved-issues.adoc
* [MTV-3237](https://issues.redhat.com/browse/MTV-3237)
* [MTV 2.9.4 resolved issues](https://github.com/kubev2v/forklift-documentation/blob/59ab23bd8f17c2ad3fe85203c12f855fc8d8c1e5/documentation/modules/rn-2-9-4-resolved-issues.adoc)
> MTV-3237: Release Notes for MTV 2.9.4

- documentation/doc-Release_notes/master.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/rn-2-9-5-resolved-issues.adoc
* [MTV-3524](https://issues.redhat.com/browse/MTV-3524)
> MTV-3524-Release-Notes-and-Attributes-MTV2.9.5
