kubev2v/forklift-documentation

- README.md
OpenShift Kubernetes Engine is a Downstream offering by Red Hat. 
The Upstream distribution for OpenShift (both OKE and OCP) is OKD ( https://www.okd.io/ )
IMHO this is the correct way to express it. Could we please consider this change?
> OKE --> OKD

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-source-provider.adoc
This PR corrects the description of how to add a VMware source provider. The previous wording specified "ESXi" for the details and credentials, whereas this should be "VCenter"
> Changed references from ESXi to vCenter when adding source provider

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-vddk-to-mtv.adoc
The Universal Base Image (UBI) provided by Red Hat is scanned for vulnerabilities, so using it ensures better security.
> Bug 1946273 - Replace busybox with UBI for VDDK image build

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/uninstalling-mtv-cli.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1945328
Preview build: https://606593475a2bae000785d712--distracted-shaw-5cd1c3.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#uninstalling-mtv-cli_forklift
Ready for QE
> BZ1945328: Delete OAuthClient in CLI uninstall

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/adding-vddk-to-mtv.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1946273
The Universal Base Image (UBI) provided by Red Hat is scanned for vulnerabilities, so using it ensures better security.
Build preview: https://deploy-preview-94--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#adding-vddk-to-mtv_forklift
> Replace busybox with UBI for VDDK image build

- documentation/doc-Migration_Toolkit_for_Virtualization/modules/common-attributes.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/installing-mtv-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/migrating-virtual-machines-cli.adoc
- documentation/doc-Migration_Toolkit_for_Virtualization/modules/uninstalling-mtv-ui.adoc
The API version of forklift has been promoted to v1beta1, so we need to reflect it in examples.
The downstream product short name has been changed to MTV, so we need to update the configuration.
> Update downstream product short name. Use apiVersion v1beta1.

- documentation/modules/uninstalling-mtv-cli.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1969852
Preview: https://deploy-preview-143--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#uninstalling-mtv-cli_forklift
> bz1969852-oauth-delete

- documentation/modules/using-must-gather.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1996971
Preview: https://deploy-preview-195--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#using-must-gather_forklift
> BZ1996971: Remove metrics and Prometheus from must-gather module

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/about-cold-warm-migration.adoc
https://issues.redhat.com/browse/MTV-79
Changes:
- Supported storage section moved to Prerequisites.
- Warm and cold migration section moved to Migrating VMs
- CRs and services, workflow sections moved to Troubleshooting > Architecture.
Previews: 
Storage: https://deploy-preview-213--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#about-storage_forklift
Warm and cold migration: https://deploy-preview-213--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#about-cold-warm-migration_forklift
Architecture: https://deploy-preview-213--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#architecture
> MTV-79: Moving architecture modules to Troubleshooting

- documentation/modules/installing-mtv-operator.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2010070
"v" removed from startingCSV field for both upstream and downstream docs
Preview: https://deploy-preview-215--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#installing-mtv-operator_forklift
> BZ2010070: Fix startingCSV

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/migration-plan-options-ui.adoc
- documentation/modules/rn-2.2.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2022654
Previews:
https://deploy-preview-244--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migration-plan-options-ui_forklift
https://deploy-preview-244--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-22_forklift
> BZ2022654: Deleting plan does not delete temporary resources

- documentation/modules/upgrading-mtv-ui.adoc
For MTV 2.2
https://bugzilla.redhat.com/show_bug.cgi?id=2031709
Catalog source pod restart required to upgrade MTV 2.1 to MTV 2.2
Direct link to doc preview: 
https://deploy-preview-276--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#upgrading-mtv-ui_forklift
> BZ2031709: Catalog source pod restart required to upgrade MTV 2.1 to MTV 2.2

- documentation/modules/rn-2.2.adoc
For MTV 2.2 
https://bugzilla.redhat.com/show_bug.cgi?id=2031649
Direct link to doc preview:
https://deploy-preview-274--forklift-documentation.netlify.app/documentation/doc-release_notes/master/#known-issues-22_forklift
> Bz2031649 vm migration is marked as succeeded when vm resource is deleted during image conversion stage

- documentation/modules/obtaining-vmware-fingerprint.adoc
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2050738.
Updated user-replaceable text to indicate that an FQDN or IP address is necessary.
Preview: https://deploy-preview-283--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#obtaining-vmware-fingerprint_forklift
> BZ2050738: Obtaining the SHA-1 fingerprint of a vCenter host" section - Fix vCenter host address

- _config.yml
- documentation/modules/common-attributes.adoc
- documentation/modules/installing-mtv-operator.adoc
- documentation/modules/upgrading-mtv-ui.adoc
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=2061650
Target MTV 2.2.
Preview:
https://deploy-preview-286--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#upgrading-mtv-ui_forklift
> 2061650 Update "MTV upgrade" section in documentation

- documentation/modules/accessing-logs-cli.adoc
- documentation/modules/adding-virt-provider.adoc
- documentation/modules/creating-network-mapping.adoc
- documentation/modules/creating-vddk-image.adoc
- documentation/modules/network-prerequisites.adoc
- documentation/modules/rn-2.0.adoc
- documentation/modules/storage-support.adoc
- documentation/modules/upgrading-mtv-ui.adoc
DO NOT MERGE BEFORE 2.3 RELEASE
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2037652
This applies to 2.3 and later.
Updated note for 2.3, such that what was previously a default setting needs to be configured in 2.3.
Preview:
https://deploy-preview-284--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#about-storage_forklift
> 2037652 - NFS StorageProfile resource should be edited with accessModes and volumeMode values before migration

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-virt-provider.adoc
MTV 2.2
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2050724
Splits the "Adding Providers" in _Installing and using the Migration Toolkit for Virtualization_ into two subsections, _Adding source providers_ and _Adding destination providers_.
Preview: https://deploy-preview-292--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#adding-providers
> Split "Adding Providers" in the MTV user guide into source providers and destination providers 

- documentation/modules/creating-validation-rule.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/retrieving-validation-service-json.adoc
- documentation/modules/rhv-prerequisites.adoc
MTV 2.2+
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2067152
Replaces "www.example.com" in MTV documentation.
> Replace "www.example.com" with "fqdn" in MTV repo

- documentation/modules/migrating-virtual-machines-cli.adoc
Bug fix.
MTV 2.3
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2067054
Remove "base64-encodes" from step 2 of the procedure for adding a source provider.
Preview: https://deploy-preview-299--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift
> Remove "base64-encoded" from source provider instructions [2nd try]

- documentation/modules/migrating-virtual-machines-cli.adoc
Fixes error in https://github.com/konveyor/forklift-documentation/pull/315. 
Removes "base64-encoded" from note 3 of step 1 of "Migrating VM" procedure
Preview: https://deploy-preview-316--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift
> Removed "base64-encoded" from note 3 of step 1 of "Migrating VM" procedure

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/installing-mtv-operator.adoc
- documentation/modules/obtaining-console-url.adoc
- documentation/modules/snippet_getting_web_console_url_cli.adoc
- documentation/modules/snippet_getting_web_console_url_web.adoc
2.2, 2.3
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2050713
Moved the section "Obtaining the MTV web console URL" one level higher in TOC, removed prerequisites from installation modules, and added it as a standalone module to take into account users accessing the info day 2 and forward.
Preview: https://deploy-preview-285--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#installing-the-operator
> 2050713 - [Doc] "Obtaining the MTV web console URL" requires more information/clarity

- documentation/modules/upgrading-mtv-ui.adoc
MTV 2.3
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2066604
It was decided by Avital and Richard that the callout was not needed because the text before the code block and code block itself were clear enough as is. 
Preview: https://deploy-preview-321--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#upgrading-mtv-ui_forklift
> Solves repeated callout

- documentation/modules/canceling-migration-cli.adoc
- documentation/modules/changing-precopy-intervals.adoc
- documentation/modules/upgrading-mtv-ui.adoc
MTV 2.3
In some files, the block metadata began with [source,shell...] instead of the previous [source,terminal...]. After consulting with Avital Pinnick, I've decided to revert the changes in order to maintain consistency in the repo and the larger document set.
> Replace [souce,shell..} with [source, terminal..] in repo

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/selecting-migration-network-for-vmware-source-provider.adoc
BZ2066328: Selection source provider network applies only to VMware
MTV 2.3
https://bugzilla.redhat.com/show_bug.cgi?id=2066328
> 2.3 BZ2066328: Selection source provider network applies only to VMware

- documentation/modules/creating-validation-rule.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/retrieving-validation-service-json.adoc
- documentation/modules/rhv-prerequisites.adoc
MTV 2.2 and 2.3
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2078360
In some places in the MTV documentation the attribute {rhv-short} appears instead of RHV.  This PR fixes that problem. 
It turned out that due to Red hat writing conventions and the fact that this PR must serve the upstream community, replacing {rhv-short} with RHV was not the best answer either. 
Previews:
1. _RHV prerequisites_: https://deploy-preview-326--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#rhv-prerequisites_forklift 
2. _Migrating virtual machines_: https://deploy-preview-326--forklift-documentation.netlify.app/documentation/doc-migration_toolkit_for_virtualization/master/#migrating-virtual-machines-cli_forklift 
3. _Retrieving the Inventory …
> BZ2078360{rhv-short} appears instead of RHV in MTV documentation

- documentation/modules/virt-migration-workflow.adoc
MTV 2.2
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2068879 for MTV 2.2.
Background: This chnage needed to be made in both MTV 2.2. and 2.3. The BZ was previously resolved for MTV 2.3 in https://github.com/kubev2v/forklift-documentation/pull/311 . Although the was for MTV 2.2, the PR was merged and published in version 2.3. This PR fixes the problem for MTV 2.2 -- it is being merged into the 2.2 branch, not the "main" branch, which is now for 2.3.
> PR 311 for MTV 2.2

- documentation/modules/source-vm-prerequisites.adoc
MTV 1.7.6
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2142529 by adding note to prerequisites for all migrations.
Preview:
> Bug 2142529: VM names are automatically changed to comply with RFC 1123 DNS Subdomain

- documentation/modules/rn-2.3.adoc
MTV 2.3.4
Resolves https://issues.redhat.com/browse/MTV-436 by adding the following items to the "Known issues" section of the MTV 2.3 release notes: 
1. [Duplication of migration plan fails on storage mapping stage if source provider is RHV](https://bugzilla.redhat.com/show_bug.cgi?id=2143191) 
2. [Destination VMs in migrations with RHV souce clusters cannot boot because TPM data, such as source key dats, is not imported](https://issues.redhat.com/browse/MTV-435)
Preview:  http://file.emea.redhat.com/rhoch/0109/rn_234/html-single/#known-issues-23_release-notes [last two items].
> Additional known issues for MTV 2.3.4

- documentation/modules/migrating-virtual-machines-cli.adoc
MTV 2.3.4+
Resolves https://issues.redhat.com/browse/MTV-442 by fixing the errors listed in the Jira. 
Preview: Step 2 of http://file.emea.redhat.com/rhoch/create_provider/html-single/#migrating-virtual-machines-from-cli
> MTV-442: Update Create Provider step

- documentation/modules/creating-vddk-image.adoc
MTV 4.3.2
Resolves https://issues.redhat.com/browse/MTV-422 by specifying that users should download VDDK version 7.0.3.2.
Preview: http://file.emea.redhat.com/rhoch/vddk7/html-single/#creating-vddk-image_mtv
> MTV-422: Change VDDK container image in documentation

- documentation/modules/error-messages.adoc
- documentation/modules/storage-support.adoc
MTV 2.4
Resolves https://issues.redhat.com/browse/MTV-443 by adding a prerequisite and a troubleshooting item dealing with a migration that uses block storage and persistent volumes created with an EXT4 file system
Preview:
1. http://file.emea.redhat.com/rhoch/exta4_3/html-single/#about-storage_mtv  Second note in "Storage support and default modes."
2. http://file.emea.redhat.com/rhoch/exta4_3/html-single/#error-messages_mtv Second item in "Error messages.'
> MTV-443: Extend file system overhead for EXT4

- documentation/modules/vmware-prerequisites.adoc
MTV 4.2
Resolves: https://issues.redhat.com/browse/MTV-485 by adding a note to the VMware prerequisites stating that MTV does not support migration of Btrfs
Preview: http://file.emea.redhat.com/rhoch/btrfs/html-single/#vmware-prerequisites_mtv Note at end of prerequisites.
> MTV does not support migration of Btrfs

- documentation/modules/creating-vddk-image.adoc
MTV 2.4
Resolves https://issues.redhat.com/browse/MTV-504 by adding a line to the Dockerfile in step 6 of https://access.redhat.com/documentation/en-us/migration_toolkit_for_virtualization/2.3/html/installing_and_using_the_migration_toolkit_for_virtualization/prerequisites#creating-vddk-image_mtv
Preview: http://file.emea.redhat.com/rhoch/vddk_docker/html-single/#creating-vddk-image_mtv, step 6, line 3 of the Dockerfile.
> MTV-504: Add user to VDDK Dockerfile

- documentation/modules/vmware-prerequisites.adoc
MTV 2.4
Resolves https://issues.redhat.com/browse/MTV-488 by including "disable hibernation" in the list of VMware migration prerequisites.
Preview: http://file.emea.redhat.com/rhoch/hibernate/html-single/#vmware-prerequisites_mtv (last item in list before the note)
> MTV-488: Add disable hibernation to VM prerequisites

- documentation/modules/common-attributes.adoc
- documentation/modules/compatibility-guidelines.adoc
@ahadas @qiyuann @mavital
[MTV-465](https://issues.redhat.com/browse/MTV-465)
Adding a new clean version of the MTV 2.4.0 references notes without junk files and typos corrected.
The other ones are such a mess, I thought it's best to start from scratch.
Please, could you do the necessary review?
Thanks
**common-attributes.adoc**
Line 9:
**:ocp-version: 4.10** changed to **:ocp-version: 4.11**
Lines 17 & 18
**:project-version: 2.3
:project-z-version: 2.3.0**
changed to
**:project-version: 2.4
:project-z-version: 2.4.0**
**compatibility-guidelines.adoc**
Adding OpenStack compatibility to the table (Lines 11 to 15):
**[cols="1,1,1,1,1,1", options="header"]
.Compatible software versions
|===
|{project-full} |{ocp} |{virt} |VMware vSphere |{rhv-full}|OpenStack
|2.3.3 |4.10 or later |4.10 or …
> aa/MTV-465: Document Support Version

- documentation/modules/adding-source-provider.adoc
- documentation/modules/common-attributes.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/rhv-prerequisites.adoc
- documentation/modules/upgrading-mtv-ui.adoc
MTV 4.2
Resolves https://issues.redhat.com/browse/MTV-429 by describing how to correctly work with third-party certificates. This change affects the prerequisites for RHV migrations, the procedure for adding a RHV source provider in the UI, and the procedure for migrating virtual machines via the CLI.
Previews:
1.  Prerequisites for RHV migrations (last item) http://file.emea.redhat.com/rhoch/rhv_cred/html-single/#rhv-prerequisites_mtv
2. Procedure for adding a RHV source provider in the UI  (step 4 in section 4.1.1.2, description of "CA certificate") http://file.emea.redhat.com/rhoch/rhv_cred/html-single/#adding-source-providers
3. Procedure for migrating virtual machines via the CLI  http://file.emea.redhat.com/rhoch/rhv_cred/html-single/#migrating-virtual-machines-cli_mtv (callout 3 …
> Document RHV credentials validation

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/adding-virt-provider.adoc
- documentation/modules/osh-adding-source-provider.adoc
MTV 2.4
Partially resolves https://issues.redhat.com/browse/MTV-426 by describing how to define OpenStack source providers using the UI.
Also includes changes made to the procedures for defining other providers in the UI.
Previews:
1. Adding source providers (vmWare, RHV, and OpenStack): http://file.emea.redhat.com/rhoch/openstack_ui/html-single/#adding-source-providers  [Sorry I cannot break the file down to each of the source procviders]
2: Adding destination providers (OpenShift Virtualization): http://file.emea.redhat.com/rhoch/openstack_cli/html-single/#adding-destination-providers
> OpenStack migration using the UI

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/accessing-logs-ui.adoc
- documentation/modules/canceling-migration-ui.adoc
- documentation/modules/collected-logs-cr-info.adoc
- documentation/modules/creating-migration-plan.adoc
- documentation/modules/creating-network-mapping.adoc
- documentation/modules/creating-storage-mapping.adoc
- documentation/modules/installing-mtv-operator.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/migration-plan-options-ui.adoc
- documentation/modules/running-migration-plan.adoc
- documentation/modules/selecting-migration-network-for-virt-provider.adoc
- documentation/modules/selecting-migration-network-for-vmware-source-provider.adoc
MTV 2.4
Resolves: https://issues.redhat.com/browse/MTV-427 by changing installation instructions to reflect that the MTV web console is now being integrated to the OCP web console. 
Also partially resolves https://issues.redhat.com/browse/MTV-467 by removing the statement "You must be logged in as a user with cluster-admin privileges" in the Prerequisites of the "Migrating virtual machines" section.  That requirement still appears elsewhere in the guide.  
Previews: 
1.http://file.emea.redhat.com/rhoch/web_in_operator/html-single/#installing-mtv-operator_web
2. http://file.emea.redhat.com/rhoch/web_in_operator/html-single/#installing-mtv-operator_cli  CLI installation
3. http://file.emea.redhat.com/rhoch/web_in_operator/html-single/#migrating-virtual-machines-from-cli  cluster-admin …
> MTV-427: OCP plug-in

- documentation/modules/creating-storage-mapping.adoc
MTV 2.4
[no Jira] Updates Section 4.3, "Creating a storage mapping" to reflect changes to the UI or to cleanup aspects of the OCP plugin not covered in previous PRs.
Preview: http://file.emea.redhat.com/rhoch/cleanup_storageMapping/html-single/#creating-storage-mapping_mtv
> Cleanup: StorageMapping

- documentation/modules/adding-source-provider.adoc
- documentation/modules/adding-virt-provider.adoc
- documentation/modules/osh-adding-source-provider.adoc
- documentation/modules/selecting-migration-network-for-virt-provider.adoc
- documentation/modules/selecting-migration-network-for-vmware-source-provider.adoc
MTV 2.4
[no jira]: Updates Section 4.1, "Adding providers" to reflect changes to the UI or to cleanup aspects of the OCP plugin not covered in previous PRs.
Preview: section 4.1.1.1.1 in http://file.emea.redhat.com/rhoch/cleanup_chapter4/html-single/#adding-source-providers
> Cleanup: Adding providers

- documentation/modules/running-migration-plan.adoc
MTV 2.4
Partially resolves https://issues.redhat.com/browse/MTV-510 by updating section 4.5., "Running a migration plan"
Preview: http://file.emea.redhat.com/rhoch/cleanup_runMigPlan/html-single/#running-migration-plan_mtv
Note: I could not check the "Warm migration only" section of the text.
> Cleanup: Running a migration plan

- documentation/modules/creating-migration-plan.adoc
MTV 2.4
Partially resolves https://issues.redhat.com/browse/MTV-510 by updating Section 4.4, "Creating a migration plan" to reflect changes to the UI or to cleanup aspects of the OCP plugin not covered in previous PRs.
Preview: http://file.emea.redhat.com/rhoch/cleanup_migrationPlan/html-single/#creating-migration-plan_mtv
> Cleanup: Migration plans

- documentation/modules/mtv-resources-and-services.adoc
- documentation/modules/source-vm-prerequisites.adoc
- documentation/modules/vmware-prerequisites.adoc
MTV 2.4
Resolves https://issues.redhat.com/browse/MTV-467 by making any changes in the list that were not covered in other PRs.
Previews:  
1. http://file.emea.redhat.com/rhoch/MTV_467/html-single/#source-vm-prerequisites_mtv "Source virtual machines  prerequisites" 
2. http://file.emea.redhat.com/rhoch/MTV_467/html-single/#mtv-resources-and-services_mtv "MTV custom resources and services"
> MTV 467: Additional changes for MTV 2.4 documentation 

- documentation/modules/creating-migration-plan.adoc
- documentation/modules/creating-storage-mapping.adoc
MTV 2.4
Set 'Source volume type' as a source title for storage mapping, in case the source provider is OSP.
Based on fix: https://github.com/kubev2v/forklift-console-plugin/pull/429
> Set 'Source volume type' as an OSP source title for storage mapping

- documentation/modules/rn-2.4.adoc
- documentation/modules/selecting-migration-network-for-virt-provider.adoc
Update release-notes of 2.4 for 2.4.1:
- Drop an obsolete known issue ('transfer-network' is not used by volume populators, fixed by https://github.com/kubev2v/forklift/pull/321)
- Add a known-issue for the failure to upgrade from 2.4.0 (a result of the fix for https://github.com/kubev2v/forklift/issues/314)
Minor modifications in the `Selecting a migration network for an OpenShift Virtualization provider` section:
- Change how 'migration network' is selected for OpenShift Virtualization providers (changed while fixing https://github.com/kubev2v/forklift-console-plugin/issues/405)
- Commented out the section of verifying the 'migration network' of an OpenShift Virtualization provider (filed https://github.com/kubev2v/forklift-console-plugin/issues/441)
> Documentation updates for 2.4.1

- documentation/modules/common-attributes.adoc
Changing the *documentation/modules/common-attributes.adoc*
Line 18: *:project-z-version: 2.4.1*
> MTV-543: changing z-stream attribute for 2.4.1

- documentation/modules/adding-virt-provider.adoc
- documentation/modules/common-attributes.adoc
There's a typo in the "Adding destination providers" section: we refer to OpenStack instead of OpenShift when explaining that providing blank URL and Service account token in the add-provider dialog means the local cluster will be used. This PR replaces "local OpenStack cluster" with "local OpenShift cluster" to fix this.
> Change OpenStack to OpenShift

- documentation/modules/creating-vddk-image.adoc
MTV 2.4
[MTV-627](https://issues.redhat.com/browse/MTV-627)
Fixes the numbering of section 2.7.1 https://access.redhat.com/documentation/en-us/migration_toolkit_for_virtualization/2.4/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#creating-vddk-image_mtv
Preview: https://file.emea.redhat.com/rhoch/fix_split_procedure/html-single/#creating-vddk-image_mtv
> Procedure and additional resources fixes

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/about-cold-warm-migration.adoc
- documentation/modules/creating-migration-plan.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/openstack-prerequisites.adoc
- documentation/modules/osh-adding-source-provider.adoc
MTV 2.5 
Resolves https://issues.redhat.com/browse/MTV-550 and https://github.com/kubev2v/forklift-documentation/pull/408 by:
1. Specifying that MTV 2.5 supports only cold migration for OpenStack
2. Removing Technology Preview notifications for OpenStack migrations
Previews:
1. https://file.emea.redhat.com/rhoch/no_warm_mig_ostack/html-single/#about-mtv [OpenStack Technology Preview notice removed; OpenStack listed among providers that support cold migration]
2. https://file.emea.redhat.com/rhoch/no_warm_mig_ostack/html-single/#openstack-prerequisites_mtv [OpenStack Technology Preview notice removed from OpenStack prerequisites] 
3. https://file.emea.redhat.com/rhoch/no_warm_mig_ostack/html-single/#adding-source-providers [OpenStack Technology Preview notice removed from "Adding an …
> MTV 2.5 supports only cold migration for OpenStack

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-633 by adding a note indicating that EMS enforcement is disabled for vSphere migrations because vSphere does not comply with 2023 FIPS requirements. 
Preview: https://file.emea.redhat.com/rhoch/FIPS/html-single/#adding-source-providers [Note labeled "IMPORTANT" in section 4.1.1.1]
> vSphere migrations and 2023 FIPS

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/ostack-app-cred-auth.adoc
- documentation/modules/ostack-token-auth.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-551 by adding descriptions of how to use token authentication and application credential authentication with OpenStack source providers.
Preview: https://file.emea.redhat.com/rhoch/ostack_auth/html-single/#additional_authentication_methods_for_migrations_with_openstack_source_providers [end of OpenStack prerequisites]
> Additional authentication methods for OpenStack source providers

- documentation/modules/creating-vddk-image.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-632 by removing the phrase "or earlier" in the note that appears in "Creating a VDDK image"
Preview: https://file.emea.redhat.com/rhoch/vddk_note/html-single/#creating-vddk-image_mtv
> Edit VDDK note

- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/rhv-prerequisites.adoc
- documentation/modules/snip-migrating-luns.adoc
- documentation/modules/virt-migration-workflow.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-555 by adding a note in several places about importing direct LUNs from a RHV source provider.
Previews:
1. https://file.emea.redhat.com/rhoch/lun/html-single/#rhv-prerequisites_mtv [Last RHV prerequisite and note]
2. https://file.emea.redhat.com/rhoch/lun/html-single/#migrating-virtual-machines-cli_mtv [RHV prerequisite in "Migrating Virtual machines"
> Importing direct LUNs from RHV

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/creating-storage-mapping.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/ova-prerequisites.adoc
- documentation/modules/snippet_ova_tech_preview.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-568 by updating the MTV user guide to include information on importing OVA files.
Note. This PR does not discuss creating OVA source providers in the UI. That is part of  https://github.com/kubev2v/forklift-documentation/pull/402. 
Previews:
1. https://file.emea.redhat.com/rhoch/ova/html-single/#ova-prerequisites_mtv [OVA prerequisites]. The Technology Preview notifications in the guide in the same places as the OpenStack ones did in version 2.4 -- as shown here and in the Create Providers PR. 
2. https://file.emea.redhat.com/rhoch/ova/html-single/#creating-storage-mapping_mtv [Storage mapping step 4d].
3. https://file.emea.redhat.com/rhoch/ova/html-single/#migrating-virtual-machines-cli_mtv [Procedure step 1 -- callout 4 in YAML and …
> OVA migration

- documentation/modules/creating-network-mapping.adoc
- documentation/modules/creating-storage-mapping.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-575 by:
1. Adding an additional option to step 4 of "Creating a storage mapping."
2. Modifying the specification of the `vms` section of the `Plan` manifest for OCP source providers. 
Also adds a note about creating providers for future use to the CLI instructions. 
Previews:
1. https://file.emea.redhat.com/rhoch/ocp_ocp_mig/html-single/#creating-storage-mapping_mtv.
2. https://file.emea.redhat.com/rhoch/ocp_ocp_mig/html-single/#migrating-virtual-machines-from-cli [last note before prerequisites] 
3. https://file.emea.redhat.com/rhoch/ocp_ocp_mig/html-single/#migrating-virtual-machines-from-cli [step 7]
> OCP-OCP migration

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/non-admin-permissions-for-ui.adoc
- documentation/modules/snip_permissions-info.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-431 by:
* Adding information describing the differences between what admins and non-admins can see and do in MTV
* Discussing permission set options for non-admins 
Previews: 
1. https://file.emea.redhat.com/rhoch/non_admin/html-single/#admins-and-non-admins [Section 4.1 and 4.1.1]
2. https://file.emea.redhat.com/rhoch/non_admin/html-single/#non-admin-permissions_cli  [Section 5.1]
> Operating MTV with non-cluster admin users

- documentation/modules/canceling-migration-cli.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
MTV 2.5
[No Jira] Changes:
1. Changes <provider> to <source_provider> in the `Provider` manifest description to be consistent with the rest of the manifests in the procedure.
2. Changes {namespace} to <namespace> in the procedure for migrating VMs via CLI so that user will insert the correct namespace instead of copy-pasting openshift-mtv automatically. 
3. The same for the procedure for canceling a migration via CLI.
Previews:
1 and 2: https://file.emea.redhat.com/rhoch/minor_cli/html-single/#migrating-virtual-machines-cli_mtv [Migration using CLI]
3: https://file.emea.redhat.com/rhoch/minor_cli/html-single/#canceling-migration-cli_mtv [canceling a migration]
> Minor changes to CLI documentation

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
MTV 2.5
Resolves https://issues.redhat.com/browse/MTV-558 by adding new Providers to user guide and updating the procedures for creating providers to fit the new UI.
Previews: 
1. Source providers: https://file.emea.redhat.com/rhoch/new_providers_25/html-single/#adding-source-providers [4.1.1 through 4.1.1.5]
2. Destination providers: https://file.emea.redhat.com/rhoch/new_providers_25/html-single/#adding-destination-providers
Note: The requirement to have cluster-admin privileges for OpenShift Virtualization providers might change in a separate PR related to non-admin users.  Please ignore the issue here.
> New Providers UI

- documentation/modules/adding-source-provider.adoc
- documentation/modules/snip-provider-names.adoc
MTV 2.5.0
Resolves https://issues.redhat.com/browse/MTV-684 by adding a note about provider names to the UI instructions.
Previews:
1. https://file.emea.redhat.com/rhoch/prov_names/html-single/#adding-providers [Note added per provider]
> Provider names

- documentation/modules/adding-source-provider.adoc
- documentation/modules/creating-validation-rule.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/snip-provider-names.adoc
MTV 2.5.1
Resolves: https://issues.redhat.com/browse/MTV-717 and https://issues.redhat.com/browse/MTV-703 by:
1. Changing the description of the URL field for vSphere source providers.
2. Changing the description of the URL field for RHV source providers.
3. Removing note that said provider names cannot include "."
4-6: Removing an inconsistent "/" in some URLs. 
Previews:
1. https://file.emea.redhat.com/rhoch/251_provider_fixes/html-single/#adding-source-providers [See definitions of "URL"  for vSphere and RHV source providers; also see that note about provider names was removed]
2. https://file.emea.redhat.com/rhoch/251_provider_fixes/html-single/#migrating-virtual-machines-cli_mtv [Step 1, callout 11 and steep 2, callout 2] 
3. …
> Align description of provider properties with the UI

- documentation/modules/ova-prerequisites.adoc
MTV 5.2.1 
Resolves https://issues.redhat.com/browse/MTV-697 by changing the description in "OVA prerequisites" of which files are read by MTV. 
Preview: https://file.emea.redhat.com/rhoch/better_ova_scan/html-single/#ova-prerequisites_mtv [Section beginning "The OVA files are in one or more folders..."
> Improved OVA files scanning under NFS share

- documentation/modules/common-attributes.adoc
* [MTV-788](https://issues.redhat.com/browse/MTV-788)
Updating Z-Stream attribute to 2.5.2:
```
:project-z-version: 2.5.2
```
Please note, I cannot use this in the release notes for MTV 2.5.2, as I need to keep the version static.
> MTV-788: Updating Z-stream attributes for 2.5.2

- documentation/modules/rn-2.5.adoc
* [MTV-787](https://issues.redhat.com/browse/MTV-787)
I have added to the top of the **Resolved Issues** for MTV 2.5
I included advice to upgrade to 2.5.2 or later
With the Jira tickets being set to `Security Level:Red Hat Employee (Red Hat Employee and Contractors only)`, I would probably remove.
> MTV-787: Release Notes for 2.5.2

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/configuring-mtv-operator.adoc
- documentation/modules/mtv-settings.adoc
- documentation/modules/storage-support.adoc
MTV 2.5.3
Resolves https://issues.redhat.com/browse/MTV-810 by adding a note describing how filesystem overhead can be configured for a migration that allocates persistent volumes without CDI and whose  `storageclass` is `filesystem`.
Added scope (after comment by Arik and Liran, and clarifications with Arik): Added a new section, "Configuring the MTV Operator" to Chapter 3, which is now called "Installing and configuring the MTV Operator" 
Previews: 
1. https://file.emea.redhat.com/rhoch/overhead_config/html-single/#about-storage_mtv [third note -- notice I moved all the notes to follow the table]
2. https://file.emea.redhat.com/rhoch/overhead_config/html-single/#installing-the-operator [new introduction to Chapter 3]
3. https://file.emea.redhat.com/rhoch/overhead_config/html-single/#conf …
> Configurable filesystem overhead

- documentation/modules/migrating-virtual-machines-cli.adoc
MTV 2.5.3
Resolves https://issues.redhat.com/browse/MTV-844 by adding additional information to some callouts in the procedure for for migrating VMs using the CLI.
Preview: https://file.emea.redhat.com/rhoch/ova_ocp_cli_update/html-single/#migrating-virtual-machines-cli_mtv [
-  Step 1, `Secret` manifest — callout 2
-  Step 2, `Provider` manifest – callout 1
- Step 5, `StorageMap`manifest – callout 2
> Update CLI migration instructions to include OCP and OVA

- documentation/modules/configuring-mtv-operator.adoc
- documentation/modules/rn-2.5.adoc
MTV 2.5.4
Resolves https://issues.redhat.com/browse/MTV-853 by adding items to the MTV release notes for version 2.5.4 (previews 1 and 2). The description of one new features required the adding of a row to table 3.1 of the MTV user guide (preview 3).
Previews: 
1. https://file.emea.redhat.com/rhoch/mtv_254_release_notes/html-single/#new-features-and-enhancements-25_release-notes [last item]
2. https://file.emea.redhat.com/rhoch/mtv_254_release_notes/html-single/#resolved-issues-25_release-notes [last item]
3. https://file.emea.redhat.com/rhoch/01012024/mtv_254_release_notes/html-single/#configuring-mtv-operator_mtv [last row in table]
> MTV 2.5.4 release notes

- documentation/modules/creating-vddk-image.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-805 by adding a paragraph to the introduction to "Creating a VDDK image" about the need to work with a file system that preserves symbolic links. The point is repeated in a new prerequisite as well.  
Preview: https://file.emea.redhat.com/rhoch/symlinks/#creating-vddk-image_mtv
> Highlighting symlinks

- documentation/modules/adding-source-provider.adoc
Resolves: https://issues.redhat.com/browse/MTV-809
MTV 2.6.0
Preview:
> MTV-809: OCP to OCP migrations require a minimum cluster version of 4.13

- documentation/modules/vmware-prerequisites.adoc
* [MTV-965](https://issues.redhat.com/browse/MTV-965)
```
* To access the virtual machine using a pre-migration hook, link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Tools] must be installed on the source virtual machine.
```
> MTV-965: doc improvement - VMware prerequisites section reowrded as it is no longer required

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/migrating-virtual-machines-cli.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/ostack-app-cred-auth.adoc
- documentation/modules/ostack-token-auth.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-859 by writing a separate CLI migration procedure per source provider.
Previews:
1. VMware: https://file.emea.redhat.com/rhoch/experiment/html-single/#new-migrating-virtual-machines-cli_vmware
2. RHV: https://file.emea.redhat.com/rhoch/experiment/html-single/#new-migrating-virtual-machines-cli_rhv
3. OVA:https://file.emea.redhat.com/rhoch/experiment/html-single/#new-migrating-virtual-machines-cli_ova
4. OpenStack: https://file.emea.redhat.com/rhoch/experiment/html-single/#new-migrating-virtual-machines-cli_ostack
5. OpenShift: https://file.emea.redhat.com/rhoch/experiment/html-single/#new-migrating-virtual-machines-cli_cnv
> Separate CLI migration procedure per source provider

- documentation/modules/rhv-prerequisites.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-271 by adding additional permissions to the RHV prerequisites.
Preview: https://file.emea.redhat.com/rhoch/rhv_permissions_260/html-single/#rhv-prerequisites_mtv
Note this PR replaces https://github.com/kubev2v/forklift-documentation/pull/426. which Sasha started.
> Revised RHV permissions

- documentation/modules/non-admin-permissions-for-ui.adoc
MTV 2,.6
Resolves https://issues.redhat.com/browse/MTV-945 by adding `secrets` permissions to Table 5.2.,  "Example permissions required for non-adminstrators to work with migration plan components but not create providers"
Preview: https://file.emea.redhat.com/rhoch/secrets/html-single/#non-admin-permissions_cli [last row of Table 5.2]
> Adding secrets permissions for non-admins

- documentation/modules/snip-migrating-luns.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-806 by removing the following sentence for the MTV user guide:  "Migration of Fibre Channel LUNs is not supported." 
Previews:
1. https://file.emea.redhat.com/rhoch/fc_luns_ok/html-single/#rhv-prerequisites_mtv [Note in RHV prerequisites]
2. https://file.emea.redhat.com/rhoch/fc_luns_ok/html-single/#migrating-virtual-machines-cli_mtv [Note in prerequisites for migrations using the CLI]
> Remove comment that FC is not supported for LUNs

- documentation/modules/configuring-mtv-operator.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-860 by adding additional to the list of Operator settings that can be configured using the CLI. 
Preview: https://file.emea.redhat.com/rhoch/cli_settings_260/html-single/#configuring-mtv-operator_mtv
> CLI settings 260

- documentation/modules/adding-source-provider.adoc
- documentation/modules/snip-certificate-options.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-557 by rewriting the procedure for working with CA certificates when creating a vSphere source provider. 
Applied to all providers except OVA. 
Preview: https://file.emea.redhat.com/rhoch/fetch_url/html-single/#adding-source-providers [steps 5 and 6 of the vSphere procedure]
> vSphere certificate options

- documentation/modules/new-migrating-virtual-machines-cli.adoc
MTV 2.6.0
Specifies that quotation marks must surround the values of `insecureSkipVerify` .
>  true and false specified in CLI procedures and callouts

- documentation/modules/configuring-mtv-operator.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-1103 for MTV 2.6.x
> Fix max_vm_inflight setting name

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
MTV 2.6
Restores the section "Selecting a migration network for a VMware source provider" to the MTV user guide.
Preview: https://file.emea.redhat.com/rhoch/vmware_mig_network/html-single/#adding-source-providers  [section 4.4.1.1.1]
> Restoring "Selecting a migration network for a VMware source provider" to the MTV user guide

- documentation/modules/common-attributes.adoc
MTV 2.6.2
Resolves https://issues.redhat.com/browse/MTV-1112 by changing the value of the `project-z-version` attribute to 2.6.2.
> MTV 2.6.2 attributes

- documentation/modules/rn-2.6.adoc
* MTV 2.6.2 release notes
* [MTV-1111](https://issues.redhat.com/browse/MTV-1111)
Resolves https://issues.redhat.com/browse/MTV-1111 by adding new text to the 2.6 release notes that is relevant to 2.6.2 (resolved issues and links to all open and resolved issues for versions 2.6.2)
> MTV 2.6.2 release notes fixed after rebase went wrong

- documentation/modules/vmware-prerequisites.adoc
MTV 2.6.3 (affects 2.5 also) 
Resolves https://issues.redhat.com/browse/MTV-1276 by adding Addditional vSphere permissions for use with OCP to the table of required permissions in https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.4/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#vmware-prerequisites_mtv
Preview:  
https://file.emea.redhat.com/rhoch/ocp_permissions_vsphere/html-single/#vmware-prerequisites_mtv [several rows added to Table 2.4]
> Additional vSphere permissions for use with OCP

- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/selecting-migration-network-for-vmware-source-provider.adoc
- documentation/modules/snip_vmware_esxi_nfc.adoc
MTV 2.6.3
Resolves https://issues.redhat.com/browse/MTV-1200 by adding a note to the MTV UI and CLI migration procedures about configuring a host on the vmWare site, rather than via MTV.  
Previews:
- https://file.emea.redhat.com/rhoch/vmware_esxi_nfc/html-single/#adding-source-providers [see note in section 4.4.1.1.1, "Selecting a migration network for a VMware source provider"
- https://file.emea.redhat.com/rhoch/vmware_esxi_nfc/html-single/#new-migrating-virtual-machines-cli_vmware [see note at the end of step 3]
> NFC-enabled vmkernel NIC migration option

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/retrieving-validation-service-json.adoc
- documentation/modules/retrieving-vmware-moref.adoc
- documentation/modules/rhv-prerequisites.adoc
MTV 2.6.3
Resolves https://issues.redhat.com/browse/MTV-1099 for MTV 2.6.x
Based on https://github.com/kubev2v/forklift-documentation/pull/507.
Previews:
New section: https://file.emea.redhat.com/rhoch/mor_26/html-single/#retrieving-vmware-moref_mtv
Notes directing users to new section: https://file.emea.redhat.com/rhoch/mor_26/html-single/#new-migrating-virtual-machines-cli_vmware [search for "moRef"]
> MTV 2.6: Retrieving the moRef of a datastore

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/snip_plan-limits.adoc
MTV 2.6
Resolves https://issues.redhat.com/browse/MTV-1341 by adding an admonition about plan size to the instructions for migrating vms by the UI and by the CLI.
Previews:
- https://file.corp.redhat.com/rhoch/plan_limits/html-single/#creating-migration-plans-ui [Note labeled "Important"]
- https://file.corp.redhat.com/rhoch/plan_limits/html-single/#migrating-virtual-machines-from-the-command-line_mtv [Second note labeled "Important"]
> Migration plan limits

- documentation/modules/creating-migration-plan-2-6-3.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
MTV 2.7.0
Resolves https://issues.redhat.com/browse/MTV-1317 (in light of https://issues.redhat.com/browse/MTV-1463) by adding a note about an issue with CentOS 7.9 and VMware migrations. 
The PR also adds a label that was previously missing from the procedure to migrate VMware VMs from the CLI.
Previews:
UI procedures:
- https://file.corp.redhat.com/rhoch/vm_name_change/html-single/#creating-migration-plan-2-6-3_provider [Admonition at end]
- https://file.corp.redhat.com/rhoch/vm_name_change/html-single/#creating-migration-plan-2-6-3_vms [Admonition at end]
CLI procedure:
- https://file.corp.redhat.com/rhoch/vm_name_change/html-single/#new-migrating-virtual-machines-cli_vmware [Step 7, callout 8 and Admonition at end of `Plan` manifest]
> VMware name change and static IP

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/mtv-performance-addendum.adoc
- documentation/modules/mtv-performance-recommendation.adoc
- documentation/modules/snip_performance.adoc
* [MTV-1352](https://issues.redhat.com/browse/MTV-1352)
* [MTV performance recommendations](https://anarnold97.github.io/MTA-Preview/MTV/mtv-performance.html#mtv-performance-recommendation_mtv)
* [MTV performance addendum](https://anarnold97.github.io/MTA-Preview/MTV/mtv-performance.html#mtv-performance-addendum_mtv)
> MTV-1352: Documentation of MTV performance 2.6

- documentation/modules/uninstalling-mtv-ui.adoc
MTV 2.6
Resolves  https://issues.redhat.com/browse/MTV-723 for the UI by revising the UI procedure for uninstalling MTV.
Preview: https://file.corp.redhat.com/rhoch/uninstall_ui/html-single/#uninstalling-mtv-ui_mtv
> Uninstalling MTV by using the UI

- documentation/modules/uninstalling-mtv-cli.adoc
MTV 2.6 
Resolves https://issues.redhat.com/browse/MTV-723 for the CLI by revising the CLI procedure for uninstalling MTV.
Preview: https://file.corp.redhat.com/rhoch/uninstall_cli/html-single/#uninstalling-mtv-cli_mtv
> Uninstalling MTV from the CLI

- documentation/modules/about-cold-warm-migration.adoc
- documentation/modules/snip_qemu-guest-agent.adoc
MTV 2.7
Resolves https://issues.redhat.com/browse/MTV-491 by adding a note about the `qemu-guest-agent ` daemon not being installed on some VMware migrations.
Preview: https://file.corp.redhat.com/rhoch/qemu_guest_agent/html-single/#cold-migration_mtv [note at end of "Cold migration".]
> Note about qemu-guest-agent for VM migrations

- documentation/modules/source-vm-prerequisites.adoc
MTV 2.7
Resolves https://issues.redhat.com/browse/MTV-1529 by modifying one of the source VM prerequisites.
Preview: https://file.corp.redhat.com/rhoch/period_to_dash/html-single/#source-vm-prerequisites_mtv
> Note in documentation for MTV-1292

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/snip_vmware-permissions.adoc
* [MTV-1608](https://issues.redhat.com/browse/MTV-1608)
* [Migrating from a VMware vSphere source provider](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1608-Missing-permissions.html#new-migrating-virtual-machines-cli_vmware)
* [Permissions needed by non-administrators to work with migration plan components](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1608-Missing-permissions.html#non-admin-permissions_cli) 
| Admonition |
| ----------------- |
| ![image](https://github.com/user-attachments/assets/3fd9bd14-9114-4596-bc4c-d178c20b937b) |
> MTV-1608: Missing permissions not correctly applied on VMware resources

- documentation/modules/common-attributes.adoc
* [MTV-1648](https://issues.redhat.com/browse/MTV-1648)
MTV z-attribute updated from `2.7.3` to `2.7.4`:
`:project-z-version: 2.7.4`
* [Software compatibility guidelines](https://anarnold97.github.io/MTA-Preview/MTV/mtv-2-7-4-attributes.html#compatibility-guidelines_mtv)
> MTV-1648: MTV 2.7.4 attributes

- documentation/modules/migration-plan-options-ui.adoc
- documentation/modules/running-migration-plan.adoc
MTV 2.7
Resolves https://issues.redhat.com/browse/MTV-808 by updating the description of how to view and download logs from the UI.
Also updates the descriptions of running migration plans and of plan options.
Previews:
-  https://file.corp.redhat.com/rhoch/get_logs_ui/html-single/#running-migration-plan_mtv [Running migration plans, includes getting logs from the Ui]
- https://file.corp.redhat.com/rhoch/get_logs_ui/html-single/#migration-plan-options-ui_mtv [Plan options]
> Getting logs from MTV UI

- documentation/modules/snip_dualboot_vm.adoc
- documentation/modules/source-vm-prerequisites.adoc
* [MTV-1741](https://issues.redhat.com/browse/MTV-1741)
* [2.4. Source virtual machine prerequisites](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1741-dual-boot.html#source-vm-prerequisites_mtv)
|      |
| ------ |
| ![image](https://github.com/user-attachments/assets/e86b5ce5-1858-466a-9b7d-54083d379a54) |
> MTV-1741: document dual-boot VMs not supported

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1785](https://issues.redhat.com/browse/MTV-1785)
* [MTV 2.7.7 resolved issues](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-7-7.html#resolved-issues-2-7-7_release-notes)
* [MTV 2.7.7 known issues](https://anarnold97.github.io/MTA-Preview/MTV/rn-2-7-7.html#known-issues-2-7_release-notes)
> MTV-1785: Release notes for MTV 2.7.7

- documentation/modules/source-vm-prerequisites.adoc
MTV 2.7
Resolves https://issues.redhat.com/browse/MTV-1550 by linking to a better list of the operating systems that support MTV and by adding more information about the use of RHEL 8 vs. RHEL 9. 
Preview: https://file.corp.redhat.com/rhoch/os_supporting_mtv/html-single/#source-vm-prerequisites_mtv
> OSs that support MTV

- documentation/modules/adding-source-provider.adoc
Resolves https://issues.redhat.com/browse/MTV-1145 by adding instructions about how to connect to a remote provider's UI, for all providers except OVA..
Preview: https://file.corp.redhat.com/rhoch/external_ui_link/html-single/#adding-source-providers [section 4.4.1.1., step 8; appears for all providers except OVA]
> MTV-1145: Remote providers web UI link

- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1854 - MTV 2.7.8 release notes](https://issues.redhat.com/browse/MTV-1854)
* [MTV 2.7.8 resolved issues](https://anarnold97.github.io/MTA-Preview/MTV/rn.2.7.8.html#resolved-issues-2-7-8_release-notes)
> MTV-1854: Release notes for MTV 2.7.8

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/configuring-mtv-operator.adoc
- documentation/modules/max-concurrent-vms.adoc
- documentation/modules/mtv-settings.adoc
MTV 2.7
Resolves https://issues.redhat.com/browse/MTV-1211 by adding information about `controller_max_vm_inflight` (shown in the UI as *Max concurrent virtual machine migrations*).
Previews:
- https://file.corp.redhat.com/rhoch/max_concur_vm/html-single/#configuring-mtv-operator_mtv  [first bullet in list and first item in Table 3.1]
- https://file.corp.redhat.com/rhoch/max_concur_vm/html-single/#max-concurrent-vms_mtv [new section]
- https://file.corp.redhat.com/rhoch/max_concur_vm/html-single/#mtv-settings_mtv [first item in Table 4.1]
> MTV-1211 Max concurrent virtual machine migrations

- documentation/modules/common-attributes.adoc
- documentation/modules/compatibility-guidelines.adoc
* [MTV-1884](https://issues.redhat.com/browse/MTV-1884)
* [Software compatibility guidelines](https://anarnold97.github.io/MTA-Preview/MTV/mtv-version.html#compatibility-guidelines_mtv)
> MTV-1884: Software Compatibility Guideline Inconsistency

- documentation/modules/configuring-mtv-operator.adoc
MTV 2.7.8
Resolves https://issues.redhat.com/browse/MTV-1936 by fixing the incorrect link. 
Preview: https://file.corp.redhat.com/rhoch/fix_link_section_33/html-single/#configuring-mtv-operator_mtv [First paragraph after the bulleted list, click the link with text "Configuring MTV settings"]
> MTV-1936 Fix link in MTV user guide 3.3

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/virt-v2v-mtv.adoc
MTV 2.8
Partly resolves https://issues.redhat.com/browse/MTV-1696 by adding a section discussing how MTV uses virt-v2v in migrations. 
Preview: https://file.corp.redhat.com/rhoch/virt_v2v_mtv/html-single/#virt-v2v-mtv_mtv
> MTV-1696: How MTV uses virt-v2v

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/about-cold-warm-migration.adoc
- documentation/modules/cold-warm-migration.adoc
- documentation/modules/mtv-migration-speed-comparison.adoc
- documentation/modules/snip_cold-warm-comparison-table.adoc
* [MTV-1852](https://issues.redhat.com/browse/MTV-1852)
* [2.1. MTV cold migration and warm migration introduction](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1852-Cold-VS-Warm-migration.html#mtv-cold-warm-migration_mtv)
* [2.2.3.  Advantages and disadvantages of cold and warm migrations](https://anarnold97.github.io/MTA-Preview/MTV/MTV-1852-Cold-VS-Warm-migration.html#warm-migration-versus-cold-migration)
> MTV-1852: Adding a Cold & Warm migration section

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/adding-source-provider.adoc
- documentation/modules/creating-migration-plan-2-8.adoc
- documentation/modules/network-prerequisites.adoc
- documentation/modules/snip-mtu-value.adoc
- documentation/modules/storage-support.adoc
MTV 2.8 
Partially resolves https://issues.redhat.com/browse/MTV-1433
Previews: 
- https://file.corp.redhat.com/rhoch/WIP_section_4/html-single/#migrating-vms-ocp-web-console_mtv  [new intro to section]
- https://file.corp.redhat.com/rhoch/WIP_section_4/html-single/#migrating-vms-mtv-ui_mtv [slightly changed intro]
- https://file.corp.redhat.com/rhoch/WIP_section_4/html-single/#migrating-vmware-ui [VMware section, all titles my abbreviations]
- https://file.corp.redhat.com/rhoch/WIP_section_4/html-single/#migrating_virtual_machines_from_rhv [RHV section]
- https://file.corp.redhat.com/rhoch/WIP_section_4/html-single/#migrating_virtual_machines_from_ostack [OpenStack]
- https://file.corp.redhat.com/rhoch/WIP_section_4/html-single/#migrating_virtual_machines_from_ova [OVA]
- …
> MTV-1433: Creating source and destination providers, separated by provider

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/accessing-logs-cli.adoc
- documentation/modules/accessing-logs-ui.adoc
- documentation/modules/canceling-migration-cli.adoc
- documentation/modules/collected-logs-cr-info.adoc
- documentation/modules/installing-mtv-operator.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/retrieving-vmware-moref.adoc
- documentation/modules/snip_vmware-permissions.adoc
- documentation/modules/uninstalling-mtv-cli.adoc
MTV 2.8 
Partially resolves https://issues.redhat.com/browse/MTV-1433 by making the following changes to the per-provider procedures for migrating VMs:
- Moves the section "Retrieving a VMware vSphere moRef" to the section of the guide related specifically to migrating VMware VMs.
- Adds the section "Cancelling a migration from the CLI" to each of the provider-based procedures,  
Previews:
https://file.corp.redhat.com/rhoch/cli_migrations_providers/html-single/#new-migrating-virtual-machines-cli_vmware [VMware section]
https://file.corp.redhat.com/rhoch/cli_migrations_providers/html-single/#new-migrating-virtual-machines-cli_rhv [RHV section]
https://file.corp.redhat.com/rhoch/cli_migrations_providers/html-single/#new-migrating-virtual-machines-cli_ostack [OpenStack] …
> MTV-1433: Minor changes to migration from CLI section

- documentation/modules/new-features-and-enhancements-2-7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
* [MTV-1945](https://issues.redhat.com/browse/MTV-1945)
* [1.2. New features and enhancements](https://anarnold97.github.io/MTA-Preview/MTV/2-7-10-rn.html#new-features-and-enhancements-2-7_release-notes)
* [1.3.1. Resolved issues 2.7.10](https://anarnold97.github.io/MTA-Preview/MTV/2-7-10-rn.html#resolved-issues-2-7-10_release-notes)
* MTV-1645 OVN secondary network is not working with multus default network override
* MTV-1743 Retain IP filed description missleading to customers
* MTV-1939 Persistent vTPM is always added to the Windows 2022 VM after conversion
* MTV-2039 Allow to specify the diskBus on a plan
> MTV-1945: Release Notes for MTV 2.7.10

- documentation/modules/adding-source-provider.adoc
- documentation/modules/snip-mtu-value.adoc
@RichardHoch  - here is the snippet fix.
Basically, you would need to do create an xref with the `{context}` already defined
```
ifdef::vmware,dest_vwmware[]
[NOTE]
====
If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer network, see xref:creating-migration-plan-2-8_vmware[Creating a migration plan].
====
endif::[]
ifdef::dest_rhv[]
[NOTE]
====
If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer …
```
> Snippet fix

- documentation/modules/known-issues-2-7.adoc
- documentation/modules/new-features-and-enhancements-2-7.adoc
- documentation/modules/rn-27-resolved-issues.adoc
MTV 2.7.11
Resolves https://issues.redhat.com/browse/MTV-2167 by creating release notes for MTV 2.7.11.
**New feature**:
[MTV-2029](https://issues.redhat.com/browse/MTV-2029): Shared disk
**Resolved issue**:
[MTV-2164](https://issues.redhat.com/browse/MTV-2164): Main controller container of forklift controller crashes during VMware migrations
**Known issue**: 
[MTV-2203](https://issues.redhat.com/browse/MTV-2203) fails for VMs backed by vSAN without VDDK
[MTV-2199](https://issues.redhat.com/browse/MTV-2199) diskBus:scsi issue
Previews: 
- https://file.corp.redhat.com/rhoch/MTV-2167-release-notes-2.7.11/html-single/#new-features-and-enhancements-2-7_release-notes [last item and the note above it]
- https://file.corp.redhat.com/rhoch/MTV-2167-release-notes-2.7.11/html-single/#resolved-issues …
> MTV-2167: Release notes for MTV 2.7.11

- documentation/modules/common-attributes.adoc
- documentation/modules/creating-migration-plan-2-8.adoc
MTV 2.8
Hold for MTV 2.8
- Resolves https://issues.redhat.com/browse/MTV-2056 by changing the name of the "Warm migration" label to "Migration type" in the MTV 2.8 documentation set. This is the first item of step 8 of "Creating a migration plan" for VMware and RHV.
- Rewrite of all of step 8 of "Creating a migration plan" for all providers. 
Previews:
- https://file.corp.redhat.com/rhoch/warm_mig_ui/html-single/#creating-migration-plan-2-8_vmware [Step 8]
- https://file.corp.redhat.com/rhoch/warm_mig_ui/html-single/#creating-migration-plan-2-8_rhv [Step 8]
- https://file.corp.redhat.com/rhoch/warm_mig_ui/html-single/#creating-migration-plan-2-8_ostack [step 8]
> To be merged for 2.8.0 - MTV-2056 Warm migration -> Migration type

- documentation/modules/configuring-mtv-operator.adoc
- documentation/modules/max-concurrent-vms.adoc
- documentation/modules/mtv-settings.adoc
MTV 2.8
Resolves https://issues.redhat.com/browse/MTV-1780 by adding by adding `controller_retain_precopy_importer_pods` to the table in https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.7/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#configuring-mtv-operator_mtv .
Martin pointed out elsewhere that we should be be referring to "parameters," not "labels", so I made that change here and in two related modules. 
Previews: 
- https://file.corp.redhat.com/rhoch/keep_importer_pods/html-single/#configuring-mtv-operator_mtv
- https://file.corp.redhat.com/rhoch/keep_importer_pods/html-single/#max-concurrent-vms_mtv
- https://file.corp.redhat.com/rhoch/keep_importer_pods/html-single/#mtv-settings_mtv
> To be merged for 2.8.0 - MTV-1780 Allow users to keep importer pods

- documentation/modules/new-migrating-virtual-machines-cli.adoc
MTV 2.8.0
Resolves https://issues.redhat.com/browse/MTV-2238 for the CLI instructions by inserting a step before creating the Plan CR. 
Preview: 
- https://file.corp.redhat.com/rhoch/cli_nad/html-single/#new-migrating-virtual-machines-cli_vmware [step 7]
- https://file.corp.redhat.com/rhoch/cli_nad/html-single/#new-migrating-virtual-machines-cli_rhv [step 6]
- https://file.corp.redhat.com/rhoch/cli_nad/html-single/#new-migrating-virtual-machines-cli_ostack [step 6]
- https://file.corp.redhat.com/rhoch/cli_nad/html-single/#new-migrating-virtual-machines-cli_ova [step 6]
- https://file.corp.redhat.com/rhoch/cli_nad/html-single/#new-migrating-virtual-machines-cli_cnv [step 6]
> CLI implementation of configuring NAD

- documentation/modules/selecting-migration-network-for-virt-provider.adoc
MTV 2.8.0
Resolves https://issues.redhat.com/browse/MTV-2238 by adding instructions on associating the network attachment definition of a transfer network with a gateway.
Preview: https://file.corp.redhat.com/rhoch/nad/html-single/#selecting-migration-network-for-virt-provider_dest_vwmware [2nd paragraph of the description, step 6 of the procedure -- repeats for all providers]
> To be merged for 2.8.0: MTV-2238: Add NAD annotation to transfer network procedure

- documentation/modules/creating-migration-plan-2-8.adoc
MTV 2.8.0
Resolves [MTV-1953](https://issues.redhat.com/browse/MTV-1953) and [MTV-2031](https://issues.redhat.com/browse/MTV-2031) by adding 4 items to the Plans details page of migrations involving VMware vSphere VMs:
- Shared Disks
- PVC name template
- Volume name template
- Network name template
Preview:
https://file.corp.redhat.com/rhoch/shared_disk_ui_setting/html-single/#creating-migration-plan-2-8_vmware [step 8, from "Shared disks" to the end of the step]
> To be merged for MTV 2.8.0: New fields in VMware Plan details page

- documentation/modules/new-migrating-virtual-machines-cli.adoc
Resolves:
- https://issues.redhat.com/browse/MTV-1430
- https://issues.redhat.com/browse/MTV-1595
- https://issues.redhat.com/browse/MTV-1596
by modifying the documentation of the `Plan` CR for migrating VMware VMs using the CLI.
Preview: 
https://file.corp.redhat.com/rhoch/template_names_cli/html-single/#new-migrating-virtual-machines-cli_vmware [step 7] @yaacov Please check changes related to template name.
> MTV 2.8.0: Changes to VMware CLI for MTV 2.8.0

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/creating-vmware-role-mtv-permissions.adoc
- documentation/modules/vmware-prerequisites.adoc
MTV 2.7
Resolves https://issues.redhat.com/browse/MTV-1608 by adding a tip on how to apply VMware permissions. The tip is aimed at making the migration process easier for users of VMware. 
Previews:
- https://file.corp.redhat.com/rhoch/vm_role/html-single/#vmware-prerequisites_mtv [Tip following table 3.4]
- https://file.corp.redhat.com/rhoch/vm_role/html-single/#creating-vmware-role-mtv-permissions_mtv
> MTV-1608: Tip on applying VMware permissions

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/creating-vmware-role-mtv-permissions.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/vmware-prerequisites.adoc
MTV 2.8.1
Resolves https://issues.redhat.com/browse/MTV-2095 by adding a new parameter, `targetName` to the `vms` section of the `Plan` CR for VMware.
Previews:
- https://file.corp.redhat.com/rhoch/non_conform_vm_name/html-single/#new-migrating-virtual-machines-cli_vmware [step 8, callout 17]
Note: This item will also be included in the MTV 2.8.1 release notes.
> TO BE MERGED FOR MTV 2.8.1: Add a name for a target VM

- documentation/modules/mtv-shared-disks.adoc
MTV 2.8.1
Resolves https://issues.redhat.com/browse/MTV-2201 by adding a few words to the description of migrating shared disks.
Preview:
https://file.corp.redhat.com/rhoch/no_shared_boot_disks/html-single/#mtv-shared-disks_vmware [2nd sentence].
> TO BE MERGED FOR MTV 2.8.1: Migrating shared boot disks is not supported

- documentation/modules/new-features-and-enhancements-2-8.adoc
MTV 2.8.1 
Fix:  Avoiding mapping a network is CLI only.
> Release notes fix: Avoiding mapping a network is CLI only

- documentation/modules/new-migrating-virtual-machines-cli.adoc
MTV 2.8.1
Resolves https://issues.redhat.com/browse/MTV-2357 by adding a new valid value, `ignored`, to `spec:map:destination:type` in the `NetworkMap` CR. 
Preview: https://file.corp.redhat.com/rhoch/no_map_network_cli/html-single/#new-migrating-virtual-machines-cli_vmware [step 4, callout 1]
> Option to not map network during creation of CLI migration plan

- documentation/modules/migration-plan-options-ui.adoc
MTV 2.8.1
Resolves https://issues.redhat.com/browse/MTV-2172 by adding a note to the "Plan options" section of the MTV user guide.
Preview: https://file.corp.redhat.com/rhoch/maps_left_in_ui_after_deletion/html-single/#migration-plan-options-ui_vmware [final note; same for all providers]
> Maps left in UI after archiving and deletion

- documentation/modules/creating-migration-plan-2-8.adoc
- documentation/modules/running-migration-plan.adoc
MTV 2.8.2
Resolves https://issues.redhat.com/browse/MTV-2223 by adding a warning against taking snapshots of VMs to the procedure for creating a migration plan and the procedure for running a migration plan:
Previews:
- https://file.corp.redhat.com/rhoch/no_snapshots_during_migs/html-single/#creating-migration-plan-2-8_vmware [Warning after step 9]
- https://file.corp.redhat.com/rhoch/no_snapshots_during_migs/html-single/#running-migration-plan_vmware [warning after step 3, procedure include "warm migration only" section, as expected] 
- https://file.corp.redhat.com/rhoch/no_snapshots_during_migs/html-single/#running-migration-plan_rhv [same, RHV] 
The PR also corrects some small formatting errors and ensures that a reference to warm migration in "Running a migration plan" is only visible …
> Warn against taking snapshots after migration starts

- README.md
- _config.yml
- assets/img/logo_location.txt
- documentation/modules/about-hooks-for-migration-plans.adoc
- documentation/modules/adding-hook-using-cli.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- index.adoc
Update configuration files:
Upstream documentaion:
https://kubev2v.github.io/forklift-documentation/
> Bump upstream doc version

- documentation/modules/adding-source-provider.adoc
- documentation/modules/new-migrating-virtual-machines-cli.adoc
- documentation/modules/snip_anti-virus-warning.adoc
MTV 2.8.3
Resolves https://issues.redhat.com/browse/MTV-2452 by adding an admonition that anti-virus software on a source VM might cause a migration to fail.
Previews:
https://file.corp.redhat.com/rhoch/anti_virus_warning/html-single/#adding-source-provider_vmware [2nd admonition]
https://file.corp.redhat.com/rhoch/anti_virus_warning/html-single/#new-migrating-virtual-machines-cli_vmware [1st admonition]
> HOLD FOR MTV 2.8.3: Warning about anti-virus software

- documentation/modules/new-migrating-virtual-machines-cli.adoc
MTV 2.8.3
Resolves https://issues.redhat.com/browse/MTV-2339 by adding the `shared` parameter to the PVC name template.
Preview: https://file.corp.redhat.com/rhoch/pvc_shared/html-single/#new-migrating-virtual-machines-cli_vmware [step 8, callout 10. Note that callout 16 refers to callout 10, so callout 16 does not need to be changed.]
> HOLD FOR MTV 2.8.3: Add shared parameter to PVC name template

- documentation/modules/common-attributes.adoc
MTV 2.8.4
Resolves https://issues.redhat.com/browse/MTV-2505 by updating the attribute file for MTV 2.8.4.
Previews:
https://file.corp.redhat.com/rhoch/MTV-2505-284-attributes/html-single/#installing-mtv-operator_cli [step 3]
https://file.corp.redhat.com/rhoch/MTV-2505-284-attributes/html-single/#using-must-gather_mtv [steps 2 and 3]
https://file.corp.redhat.com/rhoch/MTV-2505-284-attributes/html-single/#accessing-logs-cli_mtv [steps 2 and 3]
> HOLD FOR MTV 2.8.4: MTV 2.8.4 Attributes

- documentation/modules/network-prerequisites.adoc
MTV 2.8.4
Resolves https://issues.redhat.com/browse/MTV-2411 by removing an incorrect RHV port destination.
Preview: https://file.corp.redhat.com/rhoch/MTV-2411-rhv-port-req/html-single/#ports_mtv [Table 3.3]  
Replaces https://github.com/kubev2v/forklift-documentation/pull/694 [Closed].
> MTV 2.8.4: Update RHV port requirements

- documentation/modules/installing-mtv-operator.adoc
* [MTV-2899](https://issues.redhat.com/browse/MTV-2899)
Updating the attribute used in prerequisites from:
```
ocp-version: 4.18
```
to 
```
ocp-y-version: 4.18, 4.17, 4.16
```
this will update with each release to ensure we keep to OCP `n -2`
it will update to `4.19, 4.18, 4.17` with MTV 2.9.0
> MTV-2899: Updating MTV 2.9 Prerequisites

- documentation/modules/adding-source-provider.adoc
MTV 2.9.0 
Resolves https://issues.redhat.com/browse/MTV-2585 by adjusting the first step of the "Create Providers" procedure to also allow access from the Overview page.
Previews:
- https://file.corp.redhat.com/rhoch/MTV-2585-accessing-providers/html-single/#adding-source-provider_vmware [step 1]
- https://file.corp.redhat.com/rhoch/MTV-2585-accessing-providers/html-single/#adding-source-provider_rhv [step 1]
- https://file.corp.redhat.com/rhoch/MTV-2585-accessing-providers/html-single/#adding-source-provider_ostack [step 1]
- https://file.corp.redhat.com/rhoch/MTV-2585-accessing-providers/html-single/#adding-source-provider_ova [step 1]
- https://file.corp.redhat.com/rhoch/MTV-2585-accessing-providers/html-single/#adding-source-provider_cnv [step 1]
- …
> MTV-2585: Accessing Providers in MTV 2.9.0

- documentation/modules/mtv-shared-disks.adoc
```
anarnold@anarnold-thinkpadt14gen5:~/MTV/docs-migration_toolkit_for_virtualization/documentation/doc-Migration_Toolkit_for_Virtualization$ bccutil compile --lang=en-US --format html-single --open
Transforming the AsciiDoc content to DocBook XML...
Unrecognized unit of measure: a shared disk.
```
Stemming from misformatted image in `..modules/mtv-shared-disks.adoc`:
```
image::draft_workaround2.png["Remove" a shared disk]
```
> Fixing build error stemming from Unrecognized-unit-of-measure:-a-shared- disk error

- documentation/modules/adding-source-provider.adoc
- documentation/modules/creating-plan-wizard-290-vmware.adoc
MTV 2.9.4
Resolves https://issues.redhat.com/browse/MTV-3046 by adding a description of how to upload  a VDDK init image archive to to the Create VMware provider page in the UI.
Preview: https://file.corp.redhat.com/rhoch/MTV-3046_VDDK_UI/html-single/#adding-source-provider_vmware [step 2a, 3rd bullet]
> MTV-3046 Add ability to upload  a VDDK init image archive to UI

- documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
- documentation/modules/raw-copy-mode.adoc
MTV 2.9.4
Resolves https://issues.redhat.com/browse/MTV-2518 by adding a new section, "Raw copy mode" to the MTV user guide.
Preview: https://file.corp.redhat.com/rhoch/MTV-2518_RCM_for_architecture_section/html-single/#raw-copy-mode_mtv
> Raw copy mode in Architecture section

- documentation/modules/new-migrating-virtual-machines-cli.adoc
MTV 2.9.4
Resolves https://issues.redhat.com/browse/MTV-3188 by adding the  'skipGuestConversion' to the documentation for migrating VMware VMs using the CLI.
Preview: https://file.corp.redhat.com/rhoch/MTV-3188_rcm_cli/html-single/#new-migrating-virtual-machines-cli_vmware [step 8]
Replaces https://github.com/kubev2v/forklift-documentation/pull/745 [closed due to technical issue]
> MTV-3188 RCM in CLI documentation

- documentation/modules/about-cold-warm-migration.adoc
MTV 2.9.3
Resolves https://issues.redhat.com/browse/MTV-3506 by fixing the second bulleted list in https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.9/html/installing_and_using_the_migration_toolkit_for_virtualization/mtv-cold-warm-migration_mtv#about-cold-warm-migration_mtv
Preview:  https://file.corp.redhat.com/rhoch/MTV-3506_formatting/html-single/#about-cold-warm-migration_mtv [2nd bulleted list]
> MTV-3506: Fixes bulleted list in user guide section 2.4
